// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LapComMessage.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__LAP_COM_BINDING_LAPCOMMESSAGE_HPP
#define FAST_DDS_GENERATED__LAP_COM_BINDING_LAPCOMMESSAGE_HPP

#include <cstdint>
#include <utility>
#include <vector>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LAPCOMMESSAGE_SOURCE)
#define LAPCOMMESSAGE_DllAPI __declspec( dllexport )
#else
#define LAPCOMMESSAGE_DllAPI __declspec( dllimport )
#endif // LAPCOMMESSAGE_SOURCE
#else
#define LAPCOMMESSAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LAPCOMMESSAGE_DllAPI
#endif // _WIN32

namespace lap {

namespace com {

namespace binding {

/*!
 * @brief This class represents the structure LapComMessage defined by the user in the IDL file.
 * @ingroup LapComMessage
 */
class LapComMessage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LapComMessage()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LapComMessage()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LapComMessage that will be copied.
     */
    eProsima_user_DllExport LapComMessage(
            const LapComMessage& x)
    {
                    m_service_id = x.m_service_id;

                    m_instance_id = x.m_instance_id;

                    m_event_id = x.m_event_id;

                    m_timestamp_ns = x.m_timestamp_ns;

                    m_payload = x.m_payload;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LapComMessage that will be copied.
     */
    eProsima_user_DllExport LapComMessage(
            LapComMessage&& x) noexcept
    {
        m_service_id = x.m_service_id;
        m_instance_id = x.m_instance_id;
        m_event_id = x.m_event_id;
        m_timestamp_ns = x.m_timestamp_ns;
        m_payload = std::move(x.m_payload);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LapComMessage that will be copied.
     */
    eProsima_user_DllExport LapComMessage& operator =(
            const LapComMessage& x)
    {

                    m_service_id = x.m_service_id;

                    m_instance_id = x.m_instance_id;

                    m_event_id = x.m_event_id;

                    m_timestamp_ns = x.m_timestamp_ns;

                    m_payload = x.m_payload;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LapComMessage that will be copied.
     */
    eProsima_user_DllExport LapComMessage& operator =(
            LapComMessage&& x) noexcept
    {

        m_service_id = x.m_service_id;
        m_instance_id = x.m_instance_id;
        m_event_id = x.m_event_id;
        m_timestamp_ns = x.m_timestamp_ns;
        m_payload = std::move(x.m_payload);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x LapComMessage object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LapComMessage& x) const
    {
        return (m_service_id == x.m_service_id &&
           m_instance_id == x.m_instance_id &&
           m_event_id == x.m_event_id &&
           m_timestamp_ns == x.m_timestamp_ns &&
           m_payload == x.m_payload);
    }

    /*!
     * @brief Comparison operator.
     * @param x LapComMessage object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LapComMessage& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member service_id
     * @param _service_id New value for member service_id
     */
    eProsima_user_DllExport void service_id(
            uint64_t _service_id)
    {
        m_service_id = _service_id;
    }

    /*!
     * @brief This function returns the value of member service_id
     * @return Value of member service_id
     */
    eProsima_user_DllExport uint64_t service_id() const
    {
        return m_service_id;
    }

    /*!
     * @brief This function returns a reference to member service_id
     * @return Reference to member service_id
     */
    eProsima_user_DllExport uint64_t& service_id()
    {
        return m_service_id;
    }


    /*!
     * @brief This function sets a value in member instance_id
     * @param _instance_id New value for member instance_id
     */
    eProsima_user_DllExport void instance_id(
            uint64_t _instance_id)
    {
        m_instance_id = _instance_id;
    }

    /*!
     * @brief This function returns the value of member instance_id
     * @return Value of member instance_id
     */
    eProsima_user_DllExport uint64_t instance_id() const
    {
        return m_instance_id;
    }

    /*!
     * @brief This function returns a reference to member instance_id
     * @return Reference to member instance_id
     */
    eProsima_user_DllExport uint64_t& instance_id()
    {
        return m_instance_id;
    }


    /*!
     * @brief This function sets a value in member event_id
     * @param _event_id New value for member event_id
     */
    eProsima_user_DllExport void event_id(
            uint32_t _event_id)
    {
        m_event_id = _event_id;
    }

    /*!
     * @brief This function returns the value of member event_id
     * @return Value of member event_id
     */
    eProsima_user_DllExport uint32_t event_id() const
    {
        return m_event_id;
    }

    /*!
     * @brief This function returns a reference to member event_id
     * @return Reference to member event_id
     */
    eProsima_user_DllExport uint32_t& event_id()
    {
        return m_event_id;
    }


    /*!
     * @brief This function sets a value in member timestamp_ns
     * @param _timestamp_ns New value for member timestamp_ns
     */
    eProsima_user_DllExport void timestamp_ns(
            uint64_t _timestamp_ns)
    {
        m_timestamp_ns = _timestamp_ns;
    }

    /*!
     * @brief This function returns the value of member timestamp_ns
     * @return Value of member timestamp_ns
     */
    eProsima_user_DllExport uint64_t timestamp_ns() const
    {
        return m_timestamp_ns;
    }

    /*!
     * @brief This function returns a reference to member timestamp_ns
     * @return Reference to member timestamp_ns
     */
    eProsima_user_DllExport uint64_t& timestamp_ns()
    {
        return m_timestamp_ns;
    }


    /*!
     * @brief This function copies the value in member payload
     * @param _payload New value to be copied in member payload
     */
    eProsima_user_DllExport void payload(
            const std::vector<uint8_t>& _payload)
    {
        m_payload = _payload;
    }

    /*!
     * @brief This function moves the value in member payload
     * @param _payload New value to be moved in member payload
     */
    eProsima_user_DllExport void payload(
            std::vector<uint8_t>&& _payload)
    {
        m_payload = std::move(_payload);
    }

    /*!
     * @brief This function returns a constant reference to member payload
     * @return Constant reference to member payload
     */
    eProsima_user_DllExport const std::vector<uint8_t>& payload() const
    {
        return m_payload;
    }

    /*!
     * @brief This function returns a reference to member payload
     * @return Reference to member payload
     */
    eProsima_user_DllExport std::vector<uint8_t>& payload()
    {
        return m_payload;
    }



private:

    uint64_t m_service_id{0};
    uint64_t m_instance_id{0};
    uint32_t m_event_id{0};
    uint64_t m_timestamp_ns{0};
    std::vector<uint8_t> m_payload;

};

} // namespace binding

} // namespace com

} // namespace lap

#endif // _FAST_DDS_GENERATED_LAP_COM_BINDING_LAPCOMMESSAGE_HPP_


