// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LapComMessageTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "LapComMessageTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "LapComMessage.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace lap {
namespace com {
namespace binding {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_LapComMessage_type_identifier(
        TypeIdentifierPair& type_ids_LapComMessage)
{

    ReturnCode_t return_code_LapComMessage {eprosima::fastdds::dds::RETCODE_OK};
    return_code_LapComMessage =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "lap::com::binding::LapComMessage", type_ids_LapComMessage);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_LapComMessage)
    {
        StructTypeFlag struct_flags_LapComMessage = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_LapComMessage = "lap::com::binding::LapComMessage";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_LapComMessage;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_LapComMessage;
        CompleteTypeDetail detail_LapComMessage = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_LapComMessage, ann_custom_LapComMessage, type_name_LapComMessage.to_string());
        CompleteStructHeader header_LapComMessage;
        header_LapComMessage = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_LapComMessage);
        CompleteStructMemberSeq member_seq_LapComMessage;
        {
            TypeIdentifierPair type_ids_service_id;
            ReturnCode_t return_code_service_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_service_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_service_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_service_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "service_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_service_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_service_id = 0x00000000;
            bool common_service_id_ec {false};
            CommonStructMember common_service_id {TypeObjectUtils::build_common_struct_member(member_id_service_id, member_flags_service_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_service_id, common_service_id_ec))};
            if (!common_service_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure service_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_service_id = "service_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_service_id;
            ann_custom_LapComMessage.reset();
            CompleteMemberDetail detail_service_id = TypeObjectUtils::build_complete_member_detail(name_service_id, member_ann_builtin_service_id, ann_custom_LapComMessage);
            CompleteStructMember member_service_id = TypeObjectUtils::build_complete_struct_member(common_service_id, detail_service_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_LapComMessage, member_service_id);
        }
        {
            TypeIdentifierPair type_ids_instance_id;
            ReturnCode_t return_code_instance_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_instance_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_instance_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_instance_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "instance_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_instance_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_instance_id = 0x00000001;
            bool common_instance_id_ec {false};
            CommonStructMember common_instance_id {TypeObjectUtils::build_common_struct_member(member_id_instance_id, member_flags_instance_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_instance_id, common_instance_id_ec))};
            if (!common_instance_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure instance_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_instance_id = "instance_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_instance_id;
            ann_custom_LapComMessage.reset();
            CompleteMemberDetail detail_instance_id = TypeObjectUtils::build_complete_member_detail(name_instance_id, member_ann_builtin_instance_id, ann_custom_LapComMessage);
            CompleteStructMember member_instance_id = TypeObjectUtils::build_complete_struct_member(common_instance_id, detail_instance_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_LapComMessage, member_instance_id);
        }
        {
            TypeIdentifierPair type_ids_event_id;
            ReturnCode_t return_code_event_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_event_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_event_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_event_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "event_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_event_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_event_id = 0x00000002;
            bool common_event_id_ec {false};
            CommonStructMember common_event_id {TypeObjectUtils::build_common_struct_member(member_id_event_id, member_flags_event_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_event_id, common_event_id_ec))};
            if (!common_event_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure event_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_event_id = "event_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_event_id;
            ann_custom_LapComMessage.reset();
            CompleteMemberDetail detail_event_id = TypeObjectUtils::build_complete_member_detail(name_event_id, member_ann_builtin_event_id, ann_custom_LapComMessage);
            CompleteStructMember member_event_id = TypeObjectUtils::build_complete_struct_member(common_event_id, detail_event_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_LapComMessage, member_event_id);
        }
        {
            TypeIdentifierPair type_ids_timestamp_ns;
            ReturnCode_t return_code_timestamp_ns {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp_ns =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_timestamp_ns);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_ns)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp_ns Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp_ns = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp_ns = 0x00000003;
            bool common_timestamp_ns_ec {false};
            CommonStructMember common_timestamp_ns {TypeObjectUtils::build_common_struct_member(member_id_timestamp_ns, member_flags_timestamp_ns, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp_ns, common_timestamp_ns_ec))};
            if (!common_timestamp_ns_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp_ns member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp_ns = "timestamp_ns";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp_ns;
            ann_custom_LapComMessage.reset();
            CompleteMemberDetail detail_timestamp_ns = TypeObjectUtils::build_complete_member_detail(name_timestamp_ns, member_ann_builtin_timestamp_ns, ann_custom_LapComMessage);
            CompleteStructMember member_timestamp_ns = TypeObjectUtils::build_complete_struct_member(common_timestamp_ns, detail_timestamp_ns);
            TypeObjectUtils::add_complete_struct_member(member_seq_LapComMessage, member_timestamp_ns);
        }
        {
            TypeIdentifierPair type_ids_payload;
            ReturnCode_t return_code_payload {eprosima::fastdds::dds::RETCODE_OK};
            return_code_payload =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_byte_unbounded", type_ids_payload);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_payload)
            {
                return_code_payload =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_byte", type_ids_payload);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_payload)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Sequence element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_sequence_byte_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_byte_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_payload, element_identifier_anonymous_sequence_byte_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_byte_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_byte_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_payload.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_byte_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_byte_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_byte_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_byte_unbounded, element_flags_anonymous_sequence_byte_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_byte_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_byte_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_byte_unbounded", type_ids_payload))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_byte_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_payload = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_payload = 0x00000004;
            bool common_payload_ec {false};
            CommonStructMember common_payload {TypeObjectUtils::build_common_struct_member(member_id_payload, member_flags_payload, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_payload, common_payload_ec))};
            if (!common_payload_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure payload member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_payload = "payload";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_payload;
            ann_custom_LapComMessage.reset();
            CompleteMemberDetail detail_payload = TypeObjectUtils::build_complete_member_detail(name_payload, member_ann_builtin_payload, ann_custom_LapComMessage);
            CompleteStructMember member_payload = TypeObjectUtils::build_complete_struct_member(common_payload, detail_payload);
            TypeObjectUtils::add_complete_struct_member(member_seq_LapComMessage, member_payload);
        }
        CompleteStructType struct_type_LapComMessage = TypeObjectUtils::build_complete_struct_type(struct_flags_LapComMessage, header_LapComMessage, member_seq_LapComMessage);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_LapComMessage, type_name_LapComMessage.to_string(), type_ids_LapComMessage))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "lap::com::binding::LapComMessage already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace binding

} // namespace com

} // namespace lap

