// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LapComMessage.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "LapComMessage.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

lap::com::binding::LapComMessage::LapComMessage()
{
    // m_service_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@cb0ed20
    m_service_id = 0;
    // m_instance_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@8e24743
    m_instance_id = 0;
    // m_event_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@74a10858
    m_event_id = 0;
    // m_timestamp_ns com.eprosima.idl.parser.typecode.PrimitiveTypeCode@23fe1d71
    m_timestamp_ns = 0;
    // m_payload com.eprosima.idl.parser.typecode.SequenceTypeCode@28ac3dc3


}

lap::com::binding::LapComMessage::~LapComMessage()
{




}

lap::com::binding::LapComMessage::LapComMessage(
        const LapComMessage& x)
{
    m_service_id = x.m_service_id;
    m_instance_id = x.m_instance_id;
    m_event_id = x.m_event_id;
    m_timestamp_ns = x.m_timestamp_ns;
    m_payload = x.m_payload;
}

lap::com::binding::LapComMessage::LapComMessage(
        LapComMessage&& x) noexcept 
{
    m_service_id = x.m_service_id;
    m_instance_id = x.m_instance_id;
    m_event_id = x.m_event_id;
    m_timestamp_ns = x.m_timestamp_ns;
    m_payload = std::move(x.m_payload);
}

lap::com::binding::LapComMessage& lap::com::binding::LapComMessage::operator =(
        const LapComMessage& x)
{

    m_service_id = x.m_service_id;
    m_instance_id = x.m_instance_id;
    m_event_id = x.m_event_id;
    m_timestamp_ns = x.m_timestamp_ns;
    m_payload = x.m_payload;

    return *this;
}

lap::com::binding::LapComMessage& lap::com::binding::LapComMessage::operator =(
        LapComMessage&& x) noexcept
{

    m_service_id = x.m_service_id;
    m_instance_id = x.m_instance_id;
    m_event_id = x.m_event_id;
    m_timestamp_ns = x.m_timestamp_ns;
    m_payload = std::move(x.m_payload);

    return *this;
}

bool lap::com::binding::LapComMessage::operator ==(
        const LapComMessage& x) const
{

    return (m_service_id == x.m_service_id && m_instance_id == x.m_instance_id && m_event_id == x.m_event_id && m_timestamp_ns == x.m_timestamp_ns && m_payload == x.m_payload);
}

bool lap::com::binding::LapComMessage::operator !=(
        const LapComMessage& x) const
{
    return !(*this == x);
}

size_t lap::com::binding::LapComMessage::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);




    return current_alignment - initial_alignment;
}

size_t lap::com::binding::LapComMessage::getCdrSerializedSize(
        const lap::com::binding::LapComMessage& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.payload().size() > 0)
    {
        current_alignment += (data.payload().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }




    return current_alignment - initial_alignment;
}

void lap::com::binding::LapComMessage::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_service_id;
    scdr << m_instance_id;
    scdr << m_event_id;
    scdr << m_timestamp_ns;
    scdr << m_payload;

}

void lap::com::binding::LapComMessage::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_service_id;
    dcdr >> m_instance_id;
    dcdr >> m_event_id;
    dcdr >> m_timestamp_ns;
    dcdr >> m_payload;
}

/*!
 * @brief This function sets a value in member service_id
 * @param _service_id New value for member service_id
 */
void lap::com::binding::LapComMessage::service_id(
        uint64_t _service_id)
{
    m_service_id = _service_id;
}

/*!
 * @brief This function returns the value of member service_id
 * @return Value of member service_id
 */
uint64_t lap::com::binding::LapComMessage::service_id() const
{
    return m_service_id;
}

/*!
 * @brief This function returns a reference to member service_id
 * @return Reference to member service_id
 */
uint64_t& lap::com::binding::LapComMessage::service_id()
{
    return m_service_id;
}

/*!
 * @brief This function sets a value in member instance_id
 * @param _instance_id New value for member instance_id
 */
void lap::com::binding::LapComMessage::instance_id(
        uint64_t _instance_id)
{
    m_instance_id = _instance_id;
}

/*!
 * @brief This function returns the value of member instance_id
 * @return Value of member instance_id
 */
uint64_t lap::com::binding::LapComMessage::instance_id() const
{
    return m_instance_id;
}

/*!
 * @brief This function returns a reference to member instance_id
 * @return Reference to member instance_id
 */
uint64_t& lap::com::binding::LapComMessage::instance_id()
{
    return m_instance_id;
}

/*!
 * @brief This function sets a value in member event_id
 * @param _event_id New value for member event_id
 */
void lap::com::binding::LapComMessage::event_id(
        uint32_t _event_id)
{
    m_event_id = _event_id;
}

/*!
 * @brief This function returns the value of member event_id
 * @return Value of member event_id
 */
uint32_t lap::com::binding::LapComMessage::event_id() const
{
    return m_event_id;
}

/*!
 * @brief This function returns a reference to member event_id
 * @return Reference to member event_id
 */
uint32_t& lap::com::binding::LapComMessage::event_id()
{
    return m_event_id;
}

/*!
 * @brief This function sets a value in member timestamp_ns
 * @param _timestamp_ns New value for member timestamp_ns
 */
void lap::com::binding::LapComMessage::timestamp_ns(
        uint64_t _timestamp_ns)
{
    m_timestamp_ns = _timestamp_ns;
}

/*!
 * @brief This function returns the value of member timestamp_ns
 * @return Value of member timestamp_ns
 */
uint64_t lap::com::binding::LapComMessage::timestamp_ns() const
{
    return m_timestamp_ns;
}

/*!
 * @brief This function returns a reference to member timestamp_ns
 * @return Reference to member timestamp_ns
 */
uint64_t& lap::com::binding::LapComMessage::timestamp_ns()
{
    return m_timestamp_ns;
}

/*!
 * @brief This function copies the value in member payload
 * @param _payload New value to be copied in member payload
 */
void lap::com::binding::LapComMessage::payload(
        const std::vector<uint8_t>& _payload)
{
    m_payload = _payload;
}

/*!
 * @brief This function moves the value in member payload
 * @param _payload New value to be moved in member payload
 */
void lap::com::binding::LapComMessage::payload(
        std::vector<uint8_t>&& _payload)
{
    m_payload = std::move(_payload);
}

/*!
 * @brief This function returns a constant reference to member payload
 * @return Constant reference to member payload
 */
const std::vector<uint8_t>& lap::com::binding::LapComMessage::payload() const
{
    return m_payload;
}

/*!
 * @brief This function returns a reference to member payload
 * @return Reference to member payload
 */
std::vector<uint8_t>& lap::com::binding::LapComMessage::payload()
{
    return m_payload;
}

size_t lap::com::binding::LapComMessage::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool lap::com::binding::LapComMessage::isKeyDefined()
{
    return false;
}

void lap::com::binding::LapComMessage::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
         
}



