// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LapComMessage.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_LAP_COM_BINDING_LAPCOMMESSAGE_H_
#define _FAST_DDS_GENERATED_LAP_COM_BINDING_LAPCOMMESSAGE_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LapComMessage_SOURCE)
#define LapComMessage_DllAPI __declspec( dllexport )
#else
#define LapComMessage_DllAPI __declspec( dllimport )
#endif // LapComMessage_SOURCE
#else
#define LapComMessage_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LapComMessage_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace lap {
    namespace com {
        namespace binding {
            /*!
             * @brief This class represents the structure LapComMessage defined by the user in the IDL file.
             * @ingroup LAPCOMMESSAGE
             */
            class LapComMessage
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport LapComMessage();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~LapComMessage();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object lap::com::binding::LapComMessage that will be copied.
                 */
                eProsima_user_DllExport LapComMessage(
                        const LapComMessage& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object lap::com::binding::LapComMessage that will be copied.
                 */
                eProsima_user_DllExport LapComMessage(
                        LapComMessage&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object lap::com::binding::LapComMessage that will be copied.
                 */
                eProsima_user_DllExport LapComMessage& operator =(
                        const LapComMessage& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object lap::com::binding::LapComMessage that will be copied.
                 */
                eProsima_user_DllExport LapComMessage& operator =(
                        LapComMessage&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x lap::com::binding::LapComMessage object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const LapComMessage& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x lap::com::binding::LapComMessage object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const LapComMessage& x) const;

                /*!
                 * @brief This function sets a value in member service_id
                 * @param _service_id New value for member service_id
                 */
                eProsima_user_DllExport void service_id(
                        uint64_t _service_id);

                /*!
                 * @brief This function returns the value of member service_id
                 * @return Value of member service_id
                 */
                eProsima_user_DllExport uint64_t service_id() const;

                /*!
                 * @brief This function returns a reference to member service_id
                 * @return Reference to member service_id
                 */
                eProsima_user_DllExport uint64_t& service_id();

                /*!
                 * @brief This function sets a value in member instance_id
                 * @param _instance_id New value for member instance_id
                 */
                eProsima_user_DllExport void instance_id(
                        uint64_t _instance_id);

                /*!
                 * @brief This function returns the value of member instance_id
                 * @return Value of member instance_id
                 */
                eProsima_user_DllExport uint64_t instance_id() const;

                /*!
                 * @brief This function returns a reference to member instance_id
                 * @return Reference to member instance_id
                 */
                eProsima_user_DllExport uint64_t& instance_id();

                /*!
                 * @brief This function sets a value in member event_id
                 * @param _event_id New value for member event_id
                 */
                eProsima_user_DllExport void event_id(
                        uint32_t _event_id);

                /*!
                 * @brief This function returns the value of member event_id
                 * @return Value of member event_id
                 */
                eProsima_user_DllExport uint32_t event_id() const;

                /*!
                 * @brief This function returns a reference to member event_id
                 * @return Reference to member event_id
                 */
                eProsima_user_DllExport uint32_t& event_id();

                /*!
                 * @brief This function sets a value in member timestamp_ns
                 * @param _timestamp_ns New value for member timestamp_ns
                 */
                eProsima_user_DllExport void timestamp_ns(
                        uint64_t _timestamp_ns);

                /*!
                 * @brief This function returns the value of member timestamp_ns
                 * @return Value of member timestamp_ns
                 */
                eProsima_user_DllExport uint64_t timestamp_ns() const;

                /*!
                 * @brief This function returns a reference to member timestamp_ns
                 * @return Reference to member timestamp_ns
                 */
                eProsima_user_DllExport uint64_t& timestamp_ns();

                /*!
                 * @brief This function copies the value in member payload
                 * @param _payload New value to be copied in member payload
                 */
                eProsima_user_DllExport void payload(
                        const std::vector<uint8_t>& _payload);

                /*!
                 * @brief This function moves the value in member payload
                 * @param _payload New value to be moved in member payload
                 */
                eProsima_user_DllExport void payload(
                        std::vector<uint8_t>&& _payload);

                /*!
                 * @brief This function returns a constant reference to member payload
                 * @return Constant reference to member payload
                 */
                eProsima_user_DllExport const std::vector<uint8_t>& payload() const;

                /*!
                 * @brief This function returns a reference to member payload
                 * @return Reference to member payload
                 */
                eProsima_user_DllExport std::vector<uint8_t>& payload();

                /*!
                 * @brief This function returns the maximum serialized size of an object
                 * depending on the buffer alignment.
                 * @param current_alignment Buffer alignment.
                 * @return Maximum serialized size.
                 */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const lap::com::binding::LapComMessage& data,
                        size_t current_alignment = 0);


                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);



                /*!
                 * @brief This function returns the maximum serialized size of the Key of an object
                 * depending on the buffer alignment.
                 * @param current_alignment Buffer alignment.
                 * @return Maximum serialized size.
                 */
                eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function tells you if the Key has been defined for this type
                 */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                 * @brief This function serializes the key members of an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;

            private:

                uint64_t m_service_id;
                uint64_t m_instance_id;
                uint32_t m_event_id;
                uint64_t m_timestamp_ns;
                std::vector<uint8_t> m_payload;
            };
        } // namespace binding
    } // namespace com
} // namespace lap

#endif // _FAST_DDS_GENERATED_LAP_COM_BINDING_LAPCOMMESSAGE_H_