// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SensorFusionServiceCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD3_SENSORFUSIONSERVICECDRAUX_HPP
#define FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD3_SENSORFUSIONSERVICECDRAUX_HPP

#include "SensorFusionService.hpp"

constexpr uint32_t lap_examples_helloworld3_GetDiagnosticsRequest_max_cdr_typesize {28UL};
constexpr uint32_t lap_examples_helloworld3_GetDiagnosticsRequest_max_key_cdr_typesize {8UL};


constexpr uint32_t lap_examples_helloworld3_GetSensorReadingRequest_max_cdr_typesize {28UL};
constexpr uint32_t lap_examples_helloworld3_GetSensorReadingRequest_max_key_cdr_typesize {8UL};

constexpr uint32_t lap_examples_helloworld3_CalibrateDeviceRequest_max_cdr_typesize {40UL};
constexpr uint32_t lap_examples_helloworld3_CalibrateDeviceRequest_max_key_cdr_typesize {8UL};


constexpr uint32_t lap_examples_helloworld3_ComputeDigestRequest_max_cdr_typesize {288UL};
constexpr uint32_t lap_examples_helloworld3_ComputeDigestRequest_max_key_cdr_typesize {8UL};


constexpr uint32_t lap_examples_helloworld3_SensorReading_max_cdr_typesize {25UL};
constexpr uint32_t lap_examples_helloworld3_SensorReading_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_PositionUpdateEvent_max_cdr_typesize {48UL};
constexpr uint32_t lap_examples_helloworld3_PositionUpdateEvent_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_SubmitTelemetryRequest_max_cdr_typesize {32UL};
constexpr uint32_t lap_examples_helloworld3_SubmitTelemetryRequest_max_key_cdr_typesize {8UL};

constexpr uint32_t lap_examples_helloworld3_AlertInfo_max_cdr_typesize {536UL};
constexpr uint32_t lap_examples_helloworld3_AlertInfo_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_GetSensorReadingResponse_max_cdr_typesize {41UL};
constexpr uint32_t lap_examples_helloworld3_GetSensorReadingResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_GetDiagnosticsResponse_max_cdr_typesize {300UL};
constexpr uint32_t lap_examples_helloworld3_GetDiagnosticsResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_RawTelemetryEvent_max_cdr_typesize {12UL};
constexpr uint32_t lap_examples_helloworld3_RawTelemetryEvent_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_CalibrateDeviceResponse_max_cdr_typesize {280UL};
constexpr uint32_t lap_examples_helloworld3_CalibrateDeviceResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_GeoPosition_max_cdr_typesize {32UL};
constexpr uint32_t lap_examples_helloworld3_GeoPosition_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_SensorAlertEvent_max_cdr_typesize {544UL};
constexpr uint32_t lap_examples_helloworld3_SensorAlertEvent_max_key_cdr_typesize {0UL};


constexpr uint32_t lap_examples_helloworld3_DiagnosticReport_max_cdr_typesize {284UL};
constexpr uint32_t lap_examples_helloworld3_DiagnosticReport_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld3_ComputeDigestResponse_max_cdr_typesize {24UL};
constexpr uint32_t lap_examples_helloworld3_ComputeDigestResponse_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::GeoPosition& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::SensorReading& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::AlertInfo& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::DiagnosticReport& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::SensorAlertEvent& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::PositionUpdateEvent& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::RawTelemetryEvent& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::GetSensorReadingRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::GetSensorReadingResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::CalibrateDeviceRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::CalibrateDeviceResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::SubmitTelemetryRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::ComputeDigestRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::ComputeDigestResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::GetDiagnosticsRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld3::GetDiagnosticsResponse& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD3_SENSORFUSIONSERVICECDRAUX_HPP

