// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SensorFusionService.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD3_SENSORFUSIONSERVICE_HPP
#define FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD3_SENSORFUSIONSERVICE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(SENSORFUSIONSERVICE_SOURCE)
#define SENSORFUSIONSERVICE_DllAPI __declspec( dllexport )
#else
#define SENSORFUSIONSERVICE_DllAPI __declspec( dllimport )
#endif // SENSORFUSIONSERVICE_SOURCE
#else
#define SENSORFUSIONSERVICE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define SENSORFUSIONSERVICE_DllAPI
#endif // _WIN32

namespace lap {

namespace examples {

namespace helloworld3 {

const std::string SCHEMA_HASH = "64e50584ec9f900e";
/*!
 * @brief This class represents the enumeration SensorType defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
enum class SensorType : int32_t
{
    LIDAR,
    CAMERA,
    RADAR,
    ULTRASONIC,
    IMU
};
/*!
 * @brief This class represents the enumeration AlertLevel defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
enum class AlertLevel : int32_t
{
    NONE,
    INFO,
    WARNING,
    CRITICAL
};
/*!
 * @brief This class represents the enumeration DeviceState defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
enum class DeviceState : int32_t
{
    OFFLINE,
    INITIALIZING,
    ONLINE,
    ERROR,
    MAINTENANCE
};
/*!
 * @brief This class represents the structure GeoPosition defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class GeoPosition
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GeoPosition()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GeoPosition()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GeoPosition that will be copied.
     */
    eProsima_user_DllExport GeoPosition(
            const GeoPosition& x)
    {
                    m_latitude = x.m_latitude;

                    m_longitude = x.m_longitude;

                    m_altitude = x.m_altitude;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GeoPosition that will be copied.
     */
    eProsima_user_DllExport GeoPosition(
            GeoPosition&& x) noexcept
    {
        m_latitude = x.m_latitude;
        m_longitude = x.m_longitude;
        m_altitude = x.m_altitude;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GeoPosition that will be copied.
     */
    eProsima_user_DllExport GeoPosition& operator =(
            const GeoPosition& x)
    {

                    m_latitude = x.m_latitude;

                    m_longitude = x.m_longitude;

                    m_altitude = x.m_altitude;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GeoPosition that will be copied.
     */
    eProsima_user_DllExport GeoPosition& operator =(
            GeoPosition&& x) noexcept
    {

        m_latitude = x.m_latitude;
        m_longitude = x.m_longitude;
        m_altitude = x.m_altitude;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GeoPosition object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GeoPosition& x) const
    {
        return (m_latitude == x.m_latitude &&
           m_longitude == x.m_longitude &&
           m_altitude == x.m_altitude);
    }

    /*!
     * @brief Comparison operator.
     * @param x GeoPosition object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GeoPosition& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member latitude
     * @param _latitude New value for member latitude
     */
    eProsima_user_DllExport void latitude(
            double _latitude)
    {
        m_latitude = _latitude;
    }

    /*!
     * @brief This function returns the value of member latitude
     * @return Value of member latitude
     */
    eProsima_user_DllExport double latitude() const
    {
        return m_latitude;
    }

    /*!
     * @brief This function returns a reference to member latitude
     * @return Reference to member latitude
     */
    eProsima_user_DllExport double& latitude()
    {
        return m_latitude;
    }


    /*!
     * @brief This function sets a value in member longitude
     * @param _longitude New value for member longitude
     */
    eProsima_user_DllExport void longitude(
            double _longitude)
    {
        m_longitude = _longitude;
    }

    /*!
     * @brief This function returns the value of member longitude
     * @return Value of member longitude
     */
    eProsima_user_DllExport double longitude() const
    {
        return m_longitude;
    }

    /*!
     * @brief This function returns a reference to member longitude
     * @return Reference to member longitude
     */
    eProsima_user_DllExport double& longitude()
    {
        return m_longitude;
    }


    /*!
     * @brief This function sets a value in member altitude
     * @param _altitude New value for member altitude
     */
    eProsima_user_DllExport void altitude(
            double _altitude)
    {
        m_altitude = _altitude;
    }

    /*!
     * @brief This function returns the value of member altitude
     * @return Value of member altitude
     */
    eProsima_user_DllExport double altitude() const
    {
        return m_altitude;
    }

    /*!
     * @brief This function returns a reference to member altitude
     * @return Reference to member altitude
     */
    eProsima_user_DllExport double& altitude()
    {
        return m_altitude;
    }



private:

    double m_latitude{0.0};
    double m_longitude{0.0};
    double m_altitude{0.0};

};
/*!
 * @brief This class represents the structure SensorReading defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class SensorReading
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SensorReading()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SensorReading()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SensorReading that will be copied.
     */
    eProsima_user_DllExport SensorReading(
            const SensorReading& x)
    {
                    m_sensorId = x.m_sensorId;

                    m_value = x.m_value;

                    m_timestamp = x.m_timestamp;

                    m_valid = x.m_valid;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SensorReading that will be copied.
     */
    eProsima_user_DllExport SensorReading(
            SensorReading&& x) noexcept
    {
        m_sensorId = x.m_sensorId;
        m_value = x.m_value;
        m_timestamp = x.m_timestamp;
        m_valid = x.m_valid;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SensorReading that will be copied.
     */
    eProsima_user_DllExport SensorReading& operator =(
            const SensorReading& x)
    {

                    m_sensorId = x.m_sensorId;

                    m_value = x.m_value;

                    m_timestamp = x.m_timestamp;

                    m_valid = x.m_valid;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SensorReading that will be copied.
     */
    eProsima_user_DllExport SensorReading& operator =(
            SensorReading&& x) noexcept
    {

        m_sensorId = x.m_sensorId;
        m_value = x.m_value;
        m_timestamp = x.m_timestamp;
        m_valid = x.m_valid;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SensorReading object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SensorReading& x) const
    {
        return (m_sensorId == x.m_sensorId &&
           m_value == x.m_value &&
           m_timestamp == x.m_timestamp &&
           m_valid == x.m_valid);
    }

    /*!
     * @brief Comparison operator.
     * @param x SensorReading object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SensorReading& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member sensorId
     * @param _sensorId New value for member sensorId
     */
    eProsima_user_DllExport void sensorId(
            uint32_t _sensorId)
    {
        m_sensorId = _sensorId;
    }

    /*!
     * @brief This function returns the value of member sensorId
     * @return Value of member sensorId
     */
    eProsima_user_DllExport uint32_t sensorId() const
    {
        return m_sensorId;
    }

    /*!
     * @brief This function returns a reference to member sensorId
     * @return Reference to member sensorId
     */
    eProsima_user_DllExport uint32_t& sensorId()
    {
        return m_sensorId;
    }


    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(
            double _value)
    {
        m_value = _value;
    }

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport double value() const
    {
        return m_value;
    }

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport double& value()
    {
        return m_value;
    }


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp()
    {
        return m_timestamp;
    }


    /*!
     * @brief This function sets a value in member valid
     * @param _valid New value for member valid
     */
    eProsima_user_DllExport void valid(
            bool _valid)
    {
        m_valid = _valid;
    }

    /*!
     * @brief This function returns the value of member valid
     * @return Value of member valid
     */
    eProsima_user_DllExport bool valid() const
    {
        return m_valid;
    }

    /*!
     * @brief This function returns a reference to member valid
     * @return Reference to member valid
     */
    eProsima_user_DllExport bool& valid()
    {
        return m_valid;
    }



private:

    uint32_t m_sensorId{0};
    double m_value{0.0};
    uint64_t m_timestamp{0};
    bool m_valid{false};

};
/*!
 * @brief This class represents the structure AlertInfo defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class AlertInfo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AlertInfo()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AlertInfo()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AlertInfo that will be copied.
     */
    eProsima_user_DllExport AlertInfo(
            const AlertInfo& x)
    {
                    m_level = x.m_level;

                    m_source = x.m_source;

                    m_message = x.m_message;

                    m_timestamp = x.m_timestamp;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AlertInfo that will be copied.
     */
    eProsima_user_DllExport AlertInfo(
            AlertInfo&& x) noexcept
    {
        m_level = x.m_level;
        m_source = std::move(x.m_source);
        m_message = std::move(x.m_message);
        m_timestamp = x.m_timestamp;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AlertInfo that will be copied.
     */
    eProsima_user_DllExport AlertInfo& operator =(
            const AlertInfo& x)
    {

                    m_level = x.m_level;

                    m_source = x.m_source;

                    m_message = x.m_message;

                    m_timestamp = x.m_timestamp;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AlertInfo that will be copied.
     */
    eProsima_user_DllExport AlertInfo& operator =(
            AlertInfo&& x) noexcept
    {

        m_level = x.m_level;
        m_source = std::move(x.m_source);
        m_message = std::move(x.m_message);
        m_timestamp = x.m_timestamp;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x AlertInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const AlertInfo& x) const
    {
        return (m_level == x.m_level &&
           m_source == x.m_source &&
           m_message == x.m_message &&
           m_timestamp == x.m_timestamp);
    }

    /*!
     * @brief Comparison operator.
     * @param x AlertInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const AlertInfo& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member level
     * @param _level New value for member level
     */
    eProsima_user_DllExport void level(
            AlertLevel _level)
    {
        m_level = _level;
    }

    /*!
     * @brief This function returns the value of member level
     * @return Value of member level
     */
    eProsima_user_DllExport AlertLevel level() const
    {
        return m_level;
    }

    /*!
     * @brief This function returns a reference to member level
     * @return Reference to member level
     */
    eProsima_user_DllExport AlertLevel& level()
    {
        return m_level;
    }


    /*!
     * @brief This function copies the value in member source
     * @param _source New value to be copied in member source
     */
    eProsima_user_DllExport void source(
            const std::string& _source)
    {
        m_source = _source;
    }

    /*!
     * @brief This function moves the value in member source
     * @param _source New value to be moved in member source
     */
    eProsima_user_DllExport void source(
            std::string&& _source)
    {
        m_source = std::move(_source);
    }

    /*!
     * @brief This function returns a constant reference to member source
     * @return Constant reference to member source
     */
    eProsima_user_DllExport const std::string& source() const
    {
        return m_source;
    }

    /*!
     * @brief This function returns a reference to member source
     * @return Reference to member source
     */
    eProsima_user_DllExport std::string& source()
    {
        return m_source;
    }


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message)
    {
        m_message = _message;
    }

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message)
    {
        m_message = std::move(_message);
    }

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const
    {
        return m_message;
    }

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message()
    {
        return m_message;
    }


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp()
    {
        return m_timestamp;
    }



private:

    AlertLevel m_level{AlertLevel::NONE};
    std::string m_source;
    std::string m_message;
    uint64_t m_timestamp{0};

};
/*!
 * @brief This class represents the structure DiagnosticReport defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class DiagnosticReport
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DiagnosticReport()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DiagnosticReport()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DiagnosticReport that will be copied.
     */
    eProsima_user_DllExport DiagnosticReport(
            const DiagnosticReport& x)
    {
                    m_deviceId = x.m_deviceId;

                    m_state = x.m_state;

                    m_errorCount = x.m_errorCount;

                    m_uptime = x.m_uptime;

                    m_firmwareVersion = x.m_firmwareVersion;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DiagnosticReport that will be copied.
     */
    eProsima_user_DllExport DiagnosticReport(
            DiagnosticReport&& x) noexcept
    {
        m_deviceId = x.m_deviceId;
        m_state = x.m_state;
        m_errorCount = x.m_errorCount;
        m_uptime = x.m_uptime;
        m_firmwareVersion = std::move(x.m_firmwareVersion);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DiagnosticReport that will be copied.
     */
    eProsima_user_DllExport DiagnosticReport& operator =(
            const DiagnosticReport& x)
    {

                    m_deviceId = x.m_deviceId;

                    m_state = x.m_state;

                    m_errorCount = x.m_errorCount;

                    m_uptime = x.m_uptime;

                    m_firmwareVersion = x.m_firmwareVersion;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DiagnosticReport that will be copied.
     */
    eProsima_user_DllExport DiagnosticReport& operator =(
            DiagnosticReport&& x) noexcept
    {

        m_deviceId = x.m_deviceId;
        m_state = x.m_state;
        m_errorCount = x.m_errorCount;
        m_uptime = x.m_uptime;
        m_firmwareVersion = std::move(x.m_firmwareVersion);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x DiagnosticReport object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DiagnosticReport& x) const
    {
        return (m_deviceId == x.m_deviceId &&
           m_state == x.m_state &&
           m_errorCount == x.m_errorCount &&
           m_uptime == x.m_uptime &&
           m_firmwareVersion == x.m_firmwareVersion);
    }

    /*!
     * @brief Comparison operator.
     * @param x DiagnosticReport object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DiagnosticReport& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member deviceId
     * @param _deviceId New value for member deviceId
     */
    eProsima_user_DllExport void deviceId(
            uint32_t _deviceId)
    {
        m_deviceId = _deviceId;
    }

    /*!
     * @brief This function returns the value of member deviceId
     * @return Value of member deviceId
     */
    eProsima_user_DllExport uint32_t deviceId() const
    {
        return m_deviceId;
    }

    /*!
     * @brief This function returns a reference to member deviceId
     * @return Reference to member deviceId
     */
    eProsima_user_DllExport uint32_t& deviceId()
    {
        return m_deviceId;
    }


    /*!
     * @brief This function sets a value in member state
     * @param _state New value for member state
     */
    eProsima_user_DllExport void state(
            DeviceState _state)
    {
        m_state = _state;
    }

    /*!
     * @brief This function returns the value of member state
     * @return Value of member state
     */
    eProsima_user_DllExport DeviceState state() const
    {
        return m_state;
    }

    /*!
     * @brief This function returns a reference to member state
     * @return Reference to member state
     */
    eProsima_user_DllExport DeviceState& state()
    {
        return m_state;
    }


    /*!
     * @brief This function sets a value in member errorCount
     * @param _errorCount New value for member errorCount
     */
    eProsima_user_DllExport void errorCount(
            uint32_t _errorCount)
    {
        m_errorCount = _errorCount;
    }

    /*!
     * @brief This function returns the value of member errorCount
     * @return Value of member errorCount
     */
    eProsima_user_DllExport uint32_t errorCount() const
    {
        return m_errorCount;
    }

    /*!
     * @brief This function returns a reference to member errorCount
     * @return Reference to member errorCount
     */
    eProsima_user_DllExport uint32_t& errorCount()
    {
        return m_errorCount;
    }


    /*!
     * @brief This function sets a value in member uptime
     * @param _uptime New value for member uptime
     */
    eProsima_user_DllExport void uptime(
            double _uptime)
    {
        m_uptime = _uptime;
    }

    /*!
     * @brief This function returns the value of member uptime
     * @return Value of member uptime
     */
    eProsima_user_DllExport double uptime() const
    {
        return m_uptime;
    }

    /*!
     * @brief This function returns a reference to member uptime
     * @return Reference to member uptime
     */
    eProsima_user_DllExport double& uptime()
    {
        return m_uptime;
    }


    /*!
     * @brief This function copies the value in member firmwareVersion
     * @param _firmwareVersion New value to be copied in member firmwareVersion
     */
    eProsima_user_DllExport void firmwareVersion(
            const std::string& _firmwareVersion)
    {
        m_firmwareVersion = _firmwareVersion;
    }

    /*!
     * @brief This function moves the value in member firmwareVersion
     * @param _firmwareVersion New value to be moved in member firmwareVersion
     */
    eProsima_user_DllExport void firmwareVersion(
            std::string&& _firmwareVersion)
    {
        m_firmwareVersion = std::move(_firmwareVersion);
    }

    /*!
     * @brief This function returns a constant reference to member firmwareVersion
     * @return Constant reference to member firmwareVersion
     */
    eProsima_user_DllExport const std::string& firmwareVersion() const
    {
        return m_firmwareVersion;
    }

    /*!
     * @brief This function returns a reference to member firmwareVersion
     * @return Reference to member firmwareVersion
     */
    eProsima_user_DllExport std::string& firmwareVersion()
    {
        return m_firmwareVersion;
    }



private:

    uint32_t m_deviceId{0};
    DeviceState m_state{DeviceState::OFFLINE};
    uint32_t m_errorCount{0};
    double m_uptime{0.0};
    std::string m_firmwareVersion;

};
typedef double Angle;

typedef std::vector<uint8_t> RawPayload;

/*!
 * @brief This class represents the structure SensorAlertEvent defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class SensorAlertEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SensorAlertEvent()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SensorAlertEvent()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SensorAlertEvent that will be copied.
     */
    eProsima_user_DllExport SensorAlertEvent(
            const SensorAlertEvent& x)
    {
                    m_alert = x.m_alert;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SensorAlertEvent that will be copied.
     */
    eProsima_user_DllExport SensorAlertEvent(
            SensorAlertEvent&& x) noexcept
    {
        m_alert = std::move(x.m_alert);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SensorAlertEvent that will be copied.
     */
    eProsima_user_DllExport SensorAlertEvent& operator =(
            const SensorAlertEvent& x)
    {

                    m_alert = x.m_alert;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SensorAlertEvent that will be copied.
     */
    eProsima_user_DllExport SensorAlertEvent& operator =(
            SensorAlertEvent&& x) noexcept
    {

        m_alert = std::move(x.m_alert);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SensorAlertEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SensorAlertEvent& x) const
    {
        return (m_alert == x.m_alert);
    }

    /*!
     * @brief Comparison operator.
     * @param x SensorAlertEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SensorAlertEvent& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member alert
     * @param _alert New value to be copied in member alert
     */
    eProsima_user_DllExport void alert(
            const AlertInfo& _alert)
    {
        m_alert = _alert;
    }

    /*!
     * @brief This function moves the value in member alert
     * @param _alert New value to be moved in member alert
     */
    eProsima_user_DllExport void alert(
            AlertInfo&& _alert)
    {
        m_alert = std::move(_alert);
    }

    /*!
     * @brief This function returns a constant reference to member alert
     * @return Constant reference to member alert
     */
    eProsima_user_DllExport const AlertInfo& alert() const
    {
        return m_alert;
    }

    /*!
     * @brief This function returns a reference to member alert
     * @return Reference to member alert
     */
    eProsima_user_DllExport AlertInfo& alert()
    {
        return m_alert;
    }



private:

    AlertInfo m_alert;

};
/*!
 * @brief This class represents the structure PositionUpdateEvent defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class PositionUpdateEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport PositionUpdateEvent()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~PositionUpdateEvent()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object PositionUpdateEvent that will be copied.
     */
    eProsima_user_DllExport PositionUpdateEvent(
            const PositionUpdateEvent& x)
    {
                    m_position = x.m_position;

                    m_heading = x.m_heading;

                    m_speed = x.m_speed;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object PositionUpdateEvent that will be copied.
     */
    eProsima_user_DllExport PositionUpdateEvent(
            PositionUpdateEvent&& x) noexcept
    {
        m_position = std::move(x.m_position);
        m_heading = x.m_heading;
        m_speed = x.m_speed;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object PositionUpdateEvent that will be copied.
     */
    eProsima_user_DllExport PositionUpdateEvent& operator =(
            const PositionUpdateEvent& x)
    {

                    m_position = x.m_position;

                    m_heading = x.m_heading;

                    m_speed = x.m_speed;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object PositionUpdateEvent that will be copied.
     */
    eProsima_user_DllExport PositionUpdateEvent& operator =(
            PositionUpdateEvent&& x) noexcept
    {

        m_position = std::move(x.m_position);
        m_heading = x.m_heading;
        m_speed = x.m_speed;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x PositionUpdateEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const PositionUpdateEvent& x) const
    {
        return (m_position == x.m_position &&
           m_heading == x.m_heading &&
           m_speed == x.m_speed);
    }

    /*!
     * @brief Comparison operator.
     * @param x PositionUpdateEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const PositionUpdateEvent& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member position
     * @param _position New value to be copied in member position
     */
    eProsima_user_DllExport void position(
            const GeoPosition& _position)
    {
        m_position = _position;
    }

    /*!
     * @brief This function moves the value in member position
     * @param _position New value to be moved in member position
     */
    eProsima_user_DllExport void position(
            GeoPosition&& _position)
    {
        m_position = std::move(_position);
    }

    /*!
     * @brief This function returns a constant reference to member position
     * @return Constant reference to member position
     */
    eProsima_user_DllExport const GeoPosition& position() const
    {
        return m_position;
    }

    /*!
     * @brief This function returns a reference to member position
     * @return Reference to member position
     */
    eProsima_user_DllExport GeoPosition& position()
    {
        return m_position;
    }


    /*!
     * @brief This function sets a value in member heading
     * @param _heading New value for member heading
     */
    eProsima_user_DllExport void heading(
            Angle _heading)
    {
        m_heading = _heading;
    }

    /*!
     * @brief This function returns the value of member heading
     * @return Value of member heading
     */
    eProsima_user_DllExport Angle heading() const
    {
        return m_heading;
    }

    /*!
     * @brief This function returns a reference to member heading
     * @return Reference to member heading
     */
    eProsima_user_DllExport Angle& heading()
    {
        return m_heading;
    }


    /*!
     * @brief This function sets a value in member speed
     * @param _speed New value for member speed
     */
    eProsima_user_DllExport void speed(
            double _speed)
    {
        m_speed = _speed;
    }

    /*!
     * @brief This function returns the value of member speed
     * @return Value of member speed
     */
    eProsima_user_DllExport double speed() const
    {
        return m_speed;
    }

    /*!
     * @brief This function returns a reference to member speed
     * @return Reference to member speed
     */
    eProsima_user_DllExport double& speed()
    {
        return m_speed;
    }



private:

    GeoPosition m_position;
    Angle m_heading{0.0};
    double m_speed{0.0};

};
/*!
 * @brief This class represents the structure RawTelemetryEvent defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class RawTelemetryEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport RawTelemetryEvent()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~RawTelemetryEvent()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object RawTelemetryEvent that will be copied.
     */
    eProsima_user_DllExport RawTelemetryEvent(
            const RawTelemetryEvent& x)
    {
                    m_channelId = x.m_channelId;

                    m_payload = x.m_payload;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object RawTelemetryEvent that will be copied.
     */
    eProsima_user_DllExport RawTelemetryEvent(
            RawTelemetryEvent&& x) noexcept
    {
        m_channelId = x.m_channelId;
        m_payload = std::move(x.m_payload);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object RawTelemetryEvent that will be copied.
     */
    eProsima_user_DllExport RawTelemetryEvent& operator =(
            const RawTelemetryEvent& x)
    {

                    m_channelId = x.m_channelId;

                    m_payload = x.m_payload;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object RawTelemetryEvent that will be copied.
     */
    eProsima_user_DllExport RawTelemetryEvent& operator =(
            RawTelemetryEvent&& x) noexcept
    {

        m_channelId = x.m_channelId;
        m_payload = std::move(x.m_payload);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x RawTelemetryEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const RawTelemetryEvent& x) const
    {
        return (m_channelId == x.m_channelId &&
           m_payload == x.m_payload);
    }

    /*!
     * @brief Comparison operator.
     * @param x RawTelemetryEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const RawTelemetryEvent& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member channelId
     * @param _channelId New value for member channelId
     */
    eProsima_user_DllExport void channelId(
            uint32_t _channelId)
    {
        m_channelId = _channelId;
    }

    /*!
     * @brief This function returns the value of member channelId
     * @return Value of member channelId
     */
    eProsima_user_DllExport uint32_t channelId() const
    {
        return m_channelId;
    }

    /*!
     * @brief This function returns a reference to member channelId
     * @return Reference to member channelId
     */
    eProsima_user_DllExport uint32_t& channelId()
    {
        return m_channelId;
    }


    /*!
     * @brief This function copies the value in member payload
     * @param _payload New value to be copied in member payload
     */
    eProsima_user_DllExport void payload(
            const std::vector<uint8_t>& _payload)
    {
        m_payload = _payload;
    }

    /*!
     * @brief This function moves the value in member payload
     * @param _payload New value to be moved in member payload
     */
    eProsima_user_DllExport void payload(
            std::vector<uint8_t>&& _payload)
    {
        m_payload = std::move(_payload);
    }

    /*!
     * @brief This function returns a constant reference to member payload
     * @return Constant reference to member payload
     */
    eProsima_user_DllExport const std::vector<uint8_t>& payload() const
    {
        return m_payload;
    }

    /*!
     * @brief This function returns a reference to member payload
     * @return Reference to member payload
     */
    eProsima_user_DllExport std::vector<uint8_t>& payload()
    {
        return m_payload;
    }



private:

    uint32_t m_channelId{0};
    std::vector<uint8_t> m_payload;

};
/*!
 * @brief This class represents the structure GetSensorReadingRequest defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class GetSensorReadingRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GetSensorReadingRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GetSensorReadingRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GetSensorReadingRequest that will be copied.
     */
    eProsima_user_DllExport GetSensorReadingRequest(
            const GetSensorReadingRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_sensorId = x.m_sensorId;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GetSensorReadingRequest that will be copied.
     */
    eProsima_user_DllExport GetSensorReadingRequest(
            GetSensorReadingRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_sensorId = x.m_sensorId;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GetSensorReadingRequest that will be copied.
     */
    eProsima_user_DllExport GetSensorReadingRequest& operator =(
            const GetSensorReadingRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_sensorId = x.m_sensorId;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GetSensorReadingRequest that will be copied.
     */
    eProsima_user_DllExport GetSensorReadingRequest& operator =(
            GetSensorReadingRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_sensorId = x.m_sensorId;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GetSensorReadingRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GetSensorReadingRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_sensorId == x.m_sensorId);
    }

    /*!
     * @brief Comparison operator.
     * @param x GetSensorReadingRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GetSensorReadingRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member sensorId
     * @param _sensorId New value for member sensorId
     */
    eProsima_user_DllExport void sensorId(
            uint32_t _sensorId)
    {
        m_sensorId = _sensorId;
    }

    /*!
     * @brief This function returns the value of member sensorId
     * @return Value of member sensorId
     */
    eProsima_user_DllExport uint32_t sensorId() const
    {
        return m_sensorId;
    }

    /*!
     * @brief This function returns a reference to member sensorId
     * @return Reference to member sensorId
     */
    eProsima_user_DllExport uint32_t& sensorId()
    {
        return m_sensorId;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    uint32_t m_sensorId{0};

};
/*!
 * @brief This class represents the structure GetSensorReadingResponse defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class GetSensorReadingResponse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GetSensorReadingResponse()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GetSensorReadingResponse()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GetSensorReadingResponse that will be copied.
     */
    eProsima_user_DllExport GetSensorReadingResponse(
            const GetSensorReadingResponse& x)
    {
                    m_requestId = x.m_requestId;

                    m_reading = x.m_reading;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GetSensorReadingResponse that will be copied.
     */
    eProsima_user_DllExport GetSensorReadingResponse(
            GetSensorReadingResponse&& x) noexcept
    {
        m_requestId = x.m_requestId;
        m_reading = std::move(x.m_reading);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GetSensorReadingResponse that will be copied.
     */
    eProsima_user_DllExport GetSensorReadingResponse& operator =(
            const GetSensorReadingResponse& x)
    {

                    m_requestId = x.m_requestId;

                    m_reading = x.m_reading;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GetSensorReadingResponse that will be copied.
     */
    eProsima_user_DllExport GetSensorReadingResponse& operator =(
            GetSensorReadingResponse&& x) noexcept
    {

        m_requestId = x.m_requestId;
        m_reading = std::move(x.m_reading);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GetSensorReadingResponse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GetSensorReadingResponse& x) const
    {
        return (m_requestId == x.m_requestId &&
           m_reading == x.m_reading);
    }

    /*!
     * @brief Comparison operator.
     * @param x GetSensorReadingResponse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GetSensorReadingResponse& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function copies the value in member reading
     * @param _reading New value to be copied in member reading
     */
    eProsima_user_DllExport void reading(
            const SensorReading& _reading)
    {
        m_reading = _reading;
    }

    /*!
     * @brief This function moves the value in member reading
     * @param _reading New value to be moved in member reading
     */
    eProsima_user_DllExport void reading(
            SensorReading&& _reading)
    {
        m_reading = std::move(_reading);
    }

    /*!
     * @brief This function returns a constant reference to member reading
     * @return Constant reference to member reading
     */
    eProsima_user_DllExport const SensorReading& reading() const
    {
        return m_reading;
    }

    /*!
     * @brief This function returns a reference to member reading
     * @return Reference to member reading
     */
    eProsima_user_DllExport SensorReading& reading()
    {
        return m_reading;
    }



private:

    uint64_t m_requestId{0};
    SensorReading m_reading;

};
/*!
 * @brief This class represents the structure CalibrateDeviceRequest defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class CalibrateDeviceRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CalibrateDeviceRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CalibrateDeviceRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CalibrateDeviceRequest that will be copied.
     */
    eProsima_user_DllExport CalibrateDeviceRequest(
            const CalibrateDeviceRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_deviceId = x.m_deviceId;

                    m_offset = x.m_offset;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CalibrateDeviceRequest that will be copied.
     */
    eProsima_user_DllExport CalibrateDeviceRequest(
            CalibrateDeviceRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_deviceId = x.m_deviceId;
        m_offset = x.m_offset;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CalibrateDeviceRequest that will be copied.
     */
    eProsima_user_DllExport CalibrateDeviceRequest& operator =(
            const CalibrateDeviceRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_deviceId = x.m_deviceId;

                    m_offset = x.m_offset;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CalibrateDeviceRequest that will be copied.
     */
    eProsima_user_DllExport CalibrateDeviceRequest& operator =(
            CalibrateDeviceRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_deviceId = x.m_deviceId;
        m_offset = x.m_offset;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CalibrateDeviceRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CalibrateDeviceRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_deviceId == x.m_deviceId &&
           m_offset == x.m_offset);
    }

    /*!
     * @brief Comparison operator.
     * @param x CalibrateDeviceRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CalibrateDeviceRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member deviceId
     * @param _deviceId New value for member deviceId
     */
    eProsima_user_DllExport void deviceId(
            uint32_t _deviceId)
    {
        m_deviceId = _deviceId;
    }

    /*!
     * @brief This function returns the value of member deviceId
     * @return Value of member deviceId
     */
    eProsima_user_DllExport uint32_t deviceId() const
    {
        return m_deviceId;
    }

    /*!
     * @brief This function returns a reference to member deviceId
     * @return Reference to member deviceId
     */
    eProsima_user_DllExport uint32_t& deviceId()
    {
        return m_deviceId;
    }


    /*!
     * @brief This function sets a value in member offset
     * @param _offset New value for member offset
     */
    eProsima_user_DllExport void offset(
            double _offset)
    {
        m_offset = _offset;
    }

    /*!
     * @brief This function returns the value of member offset
     * @return Value of member offset
     */
    eProsima_user_DllExport double offset() const
    {
        return m_offset;
    }

    /*!
     * @brief This function returns a reference to member offset
     * @return Reference to member offset
     */
    eProsima_user_DllExport double& offset()
    {
        return m_offset;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    uint32_t m_deviceId{0};
    double m_offset{0.0};

};
/*!
 * @brief This class represents the structure CalibrateDeviceResponse defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class CalibrateDeviceResponse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CalibrateDeviceResponse()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CalibrateDeviceResponse()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CalibrateDeviceResponse that will be copied.
     */
    eProsima_user_DllExport CalibrateDeviceResponse(
            const CalibrateDeviceResponse& x)
    {
                    m_requestId = x.m_requestId;

                    m_success = x.m_success;

                    m_message = x.m_message;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CalibrateDeviceResponse that will be copied.
     */
    eProsima_user_DllExport CalibrateDeviceResponse(
            CalibrateDeviceResponse&& x) noexcept
    {
        m_requestId = x.m_requestId;
        m_success = x.m_success;
        m_message = std::move(x.m_message);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CalibrateDeviceResponse that will be copied.
     */
    eProsima_user_DllExport CalibrateDeviceResponse& operator =(
            const CalibrateDeviceResponse& x)
    {

                    m_requestId = x.m_requestId;

                    m_success = x.m_success;

                    m_message = x.m_message;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CalibrateDeviceResponse that will be copied.
     */
    eProsima_user_DllExport CalibrateDeviceResponse& operator =(
            CalibrateDeviceResponse&& x) noexcept
    {

        m_requestId = x.m_requestId;
        m_success = x.m_success;
        m_message = std::move(x.m_message);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x CalibrateDeviceResponse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CalibrateDeviceResponse& x) const
    {
        return (m_requestId == x.m_requestId &&
           m_success == x.m_success &&
           m_message == x.m_message);
    }

    /*!
     * @brief Comparison operator.
     * @param x CalibrateDeviceResponse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CalibrateDeviceResponse& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member success
     * @param _success New value for member success
     */
    eProsima_user_DllExport void success(
            bool _success)
    {
        m_success = _success;
    }

    /*!
     * @brief This function returns the value of member success
     * @return Value of member success
     */
    eProsima_user_DllExport bool success() const
    {
        return m_success;
    }

    /*!
     * @brief This function returns a reference to member success
     * @return Reference to member success
     */
    eProsima_user_DllExport bool& success()
    {
        return m_success;
    }


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message)
    {
        m_message = _message;
    }

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message)
    {
        m_message = std::move(_message);
    }

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const
    {
        return m_message;
    }

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message()
    {
        return m_message;
    }



private:

    uint64_t m_requestId{0};
    bool m_success{false};
    std::string m_message;

};
/*!
 * @brief This class represents the structure SubmitTelemetryRequest defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class SubmitTelemetryRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SubmitTelemetryRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SubmitTelemetryRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SubmitTelemetryRequest that will be copied.
     */
    eProsima_user_DllExport SubmitTelemetryRequest(
            const SubmitTelemetryRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_channelId = x.m_channelId;

                    m_payload = x.m_payload;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SubmitTelemetryRequest that will be copied.
     */
    eProsima_user_DllExport SubmitTelemetryRequest(
            SubmitTelemetryRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_channelId = x.m_channelId;
        m_payload = std::move(x.m_payload);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SubmitTelemetryRequest that will be copied.
     */
    eProsima_user_DllExport SubmitTelemetryRequest& operator =(
            const SubmitTelemetryRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_channelId = x.m_channelId;

                    m_payload = x.m_payload;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SubmitTelemetryRequest that will be copied.
     */
    eProsima_user_DllExport SubmitTelemetryRequest& operator =(
            SubmitTelemetryRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_channelId = x.m_channelId;
        m_payload = std::move(x.m_payload);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SubmitTelemetryRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SubmitTelemetryRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_channelId == x.m_channelId &&
           m_payload == x.m_payload);
    }

    /*!
     * @brief Comparison operator.
     * @param x SubmitTelemetryRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SubmitTelemetryRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member channelId
     * @param _channelId New value for member channelId
     */
    eProsima_user_DllExport void channelId(
            uint32_t _channelId)
    {
        m_channelId = _channelId;
    }

    /*!
     * @brief This function returns the value of member channelId
     * @return Value of member channelId
     */
    eProsima_user_DllExport uint32_t channelId() const
    {
        return m_channelId;
    }

    /*!
     * @brief This function returns a reference to member channelId
     * @return Reference to member channelId
     */
    eProsima_user_DllExport uint32_t& channelId()
    {
        return m_channelId;
    }


    /*!
     * @brief This function copies the value in member payload
     * @param _payload New value to be copied in member payload
     */
    eProsima_user_DllExport void payload(
            const std::vector<uint8_t>& _payload)
    {
        m_payload = _payload;
    }

    /*!
     * @brief This function moves the value in member payload
     * @param _payload New value to be moved in member payload
     */
    eProsima_user_DllExport void payload(
            std::vector<uint8_t>&& _payload)
    {
        m_payload = std::move(_payload);
    }

    /*!
     * @brief This function returns a constant reference to member payload
     * @return Constant reference to member payload
     */
    eProsima_user_DllExport const std::vector<uint8_t>& payload() const
    {
        return m_payload;
    }

    /*!
     * @brief This function returns a reference to member payload
     * @return Reference to member payload
     */
    eProsima_user_DllExport std::vector<uint8_t>& payload()
    {
        return m_payload;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    uint32_t m_channelId{0};
    std::vector<uint8_t> m_payload;

};
/*!
 * @brief This class represents the structure ComputeDigestRequest defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class ComputeDigestRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ComputeDigestRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ComputeDigestRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ComputeDigestRequest that will be copied.
     */
    eProsima_user_DllExport ComputeDigestRequest(
            const ComputeDigestRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_data = x.m_data;

                    m_algorithm = x.m_algorithm;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ComputeDigestRequest that will be copied.
     */
    eProsima_user_DllExport ComputeDigestRequest(
            ComputeDigestRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_data = std::move(x.m_data);
        m_algorithm = std::move(x.m_algorithm);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ComputeDigestRequest that will be copied.
     */
    eProsima_user_DllExport ComputeDigestRequest& operator =(
            const ComputeDigestRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_data = x.m_data;

                    m_algorithm = x.m_algorithm;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ComputeDigestRequest that will be copied.
     */
    eProsima_user_DllExport ComputeDigestRequest& operator =(
            ComputeDigestRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_data = std::move(x.m_data);
        m_algorithm = std::move(x.m_algorithm);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ComputeDigestRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ComputeDigestRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_data == x.m_data &&
           m_algorithm == x.m_algorithm);
    }

    /*!
     * @brief Comparison operator.
     * @param x ComputeDigestRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ComputeDigestRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::vector<uint8_t>& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::vector<uint8_t>&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::vector<uint8_t>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::vector<uint8_t>& data()
    {
        return m_data;
    }


    /*!
     * @brief This function copies the value in member algorithm
     * @param _algorithm New value to be copied in member algorithm
     */
    eProsima_user_DllExport void algorithm(
            const std::string& _algorithm)
    {
        m_algorithm = _algorithm;
    }

    /*!
     * @brief This function moves the value in member algorithm
     * @param _algorithm New value to be moved in member algorithm
     */
    eProsima_user_DllExport void algorithm(
            std::string&& _algorithm)
    {
        m_algorithm = std::move(_algorithm);
    }

    /*!
     * @brief This function returns a constant reference to member algorithm
     * @return Constant reference to member algorithm
     */
    eProsima_user_DllExport const std::string& algorithm() const
    {
        return m_algorithm;
    }

    /*!
     * @brief This function returns a reference to member algorithm
     * @return Reference to member algorithm
     */
    eProsima_user_DllExport std::string& algorithm()
    {
        return m_algorithm;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    std::vector<uint8_t> m_data;
    std::string m_algorithm;

};
/*!
 * @brief This class represents the structure ComputeDigestResponse defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class ComputeDigestResponse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ComputeDigestResponse()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ComputeDigestResponse()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ComputeDigestResponse that will be copied.
     */
    eProsima_user_DllExport ComputeDigestResponse(
            const ComputeDigestResponse& x)
    {
                    m_requestId = x.m_requestId;

                    m_digest = x.m_digest;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ComputeDigestResponse that will be copied.
     */
    eProsima_user_DllExport ComputeDigestResponse(
            ComputeDigestResponse&& x) noexcept
    {
        m_requestId = x.m_requestId;
        m_digest = x.m_digest;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ComputeDigestResponse that will be copied.
     */
    eProsima_user_DllExport ComputeDigestResponse& operator =(
            const ComputeDigestResponse& x)
    {

                    m_requestId = x.m_requestId;

                    m_digest = x.m_digest;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ComputeDigestResponse that will be copied.
     */
    eProsima_user_DllExport ComputeDigestResponse& operator =(
            ComputeDigestResponse&& x) noexcept
    {

        m_requestId = x.m_requestId;
        m_digest = x.m_digest;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ComputeDigestResponse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ComputeDigestResponse& x) const
    {
        return (m_requestId == x.m_requestId &&
           m_digest == x.m_digest);
    }

    /*!
     * @brief Comparison operator.
     * @param x ComputeDigestResponse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ComputeDigestResponse& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member digest
     * @param _digest New value for member digest
     */
    eProsima_user_DllExport void digest(
            uint64_t _digest)
    {
        m_digest = _digest;
    }

    /*!
     * @brief This function returns the value of member digest
     * @return Value of member digest
     */
    eProsima_user_DllExport uint64_t digest() const
    {
        return m_digest;
    }

    /*!
     * @brief This function returns a reference to member digest
     * @return Reference to member digest
     */
    eProsima_user_DllExport uint64_t& digest()
    {
        return m_digest;
    }



private:

    uint64_t m_requestId{0};
    uint64_t m_digest{0};

};
/*!
 * @brief This class represents the structure GetDiagnosticsRequest defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class GetDiagnosticsRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GetDiagnosticsRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GetDiagnosticsRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GetDiagnosticsRequest that will be copied.
     */
    eProsima_user_DllExport GetDiagnosticsRequest(
            const GetDiagnosticsRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_deviceId = x.m_deviceId;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GetDiagnosticsRequest that will be copied.
     */
    eProsima_user_DllExport GetDiagnosticsRequest(
            GetDiagnosticsRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_deviceId = x.m_deviceId;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GetDiagnosticsRequest that will be copied.
     */
    eProsima_user_DllExport GetDiagnosticsRequest& operator =(
            const GetDiagnosticsRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_deviceId = x.m_deviceId;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GetDiagnosticsRequest that will be copied.
     */
    eProsima_user_DllExport GetDiagnosticsRequest& operator =(
            GetDiagnosticsRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_deviceId = x.m_deviceId;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GetDiagnosticsRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GetDiagnosticsRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_deviceId == x.m_deviceId);
    }

    /*!
     * @brief Comparison operator.
     * @param x GetDiagnosticsRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GetDiagnosticsRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member deviceId
     * @param _deviceId New value for member deviceId
     */
    eProsima_user_DllExport void deviceId(
            uint32_t _deviceId)
    {
        m_deviceId = _deviceId;
    }

    /*!
     * @brief This function returns the value of member deviceId
     * @return Value of member deviceId
     */
    eProsima_user_DllExport uint32_t deviceId() const
    {
        return m_deviceId;
    }

    /*!
     * @brief This function returns a reference to member deviceId
     * @return Reference to member deviceId
     */
    eProsima_user_DllExport uint32_t& deviceId()
    {
        return m_deviceId;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    uint32_t m_deviceId{0};

};
/*!
 * @brief This class represents the structure GetDiagnosticsResponse defined by the user in the IDL file.
 * @ingroup SensorFusionService
 */
class GetDiagnosticsResponse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GetDiagnosticsResponse()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GetDiagnosticsResponse()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GetDiagnosticsResponse that will be copied.
     */
    eProsima_user_DllExport GetDiagnosticsResponse(
            const GetDiagnosticsResponse& x)
    {
                    m_requestId = x.m_requestId;

                    m_report = x.m_report;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GetDiagnosticsResponse that will be copied.
     */
    eProsima_user_DllExport GetDiagnosticsResponse(
            GetDiagnosticsResponse&& x) noexcept
    {
        m_requestId = x.m_requestId;
        m_report = std::move(x.m_report);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GetDiagnosticsResponse that will be copied.
     */
    eProsima_user_DllExport GetDiagnosticsResponse& operator =(
            const GetDiagnosticsResponse& x)
    {

                    m_requestId = x.m_requestId;

                    m_report = x.m_report;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GetDiagnosticsResponse that will be copied.
     */
    eProsima_user_DllExport GetDiagnosticsResponse& operator =(
            GetDiagnosticsResponse&& x) noexcept
    {

        m_requestId = x.m_requestId;
        m_report = std::move(x.m_report);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GetDiagnosticsResponse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GetDiagnosticsResponse& x) const
    {
        return (m_requestId == x.m_requestId &&
           m_report == x.m_report);
    }

    /*!
     * @brief Comparison operator.
     * @param x GetDiagnosticsResponse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GetDiagnosticsResponse& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function copies the value in member report
     * @param _report New value to be copied in member report
     */
    eProsima_user_DllExport void report(
            const DiagnosticReport& _report)
    {
        m_report = _report;
    }

    /*!
     * @brief This function moves the value in member report
     * @param _report New value to be moved in member report
     */
    eProsima_user_DllExport void report(
            DiagnosticReport&& _report)
    {
        m_report = std::move(_report);
    }

    /*!
     * @brief This function returns a constant reference to member report
     * @return Constant reference to member report
     */
    eProsima_user_DllExport const DiagnosticReport& report() const
    {
        return m_report;
    }

    /*!
     * @brief This function returns a reference to member report
     * @return Reference to member report
     */
    eProsima_user_DllExport DiagnosticReport& report()
    {
        return m_report;
    }



private:

    uint64_t m_requestId{0};
    DiagnosticReport m_report;

};

} // namespace helloworld3

} // namespace examples

} // namespace lap

#endif // _FAST_DDS_GENERATED_LAP_EXAMPLES_HELLOWORLD3_SENSORFUSIONSERVICE_HPP_


