/**
 * @file        ServiceDiscovery.hpp
 * @author      Generated by LightAP Architecture Optimizer
 * @brief       AUTOSAR R24-11 Service Discovery with Fast-DDS Integration
 * @date        2025-11-19
 * @details     Three-tier service discovery: Static Config → Discovery Server → Dynamic Discovery
 *              Conforms to AUTOSAR EXP 7.2.1 (Central Service Discovery) and SWS_CM_02201 (Static Service Connection)
 * @copyright   Copyright (c) 2025
 * @version     2.0
 */
#ifndef LAP_COM_SERVICE_DISCOVERY_HPP
#define LAP_COM_SERVICEDISCOVERY_HPP

#include "ComTypes.hpp"
#include "ServiceHandleType.hpp"
#include <core/CInstanceSpecifier.hpp>
#include <core/CResult.hpp>

#include <string>
#include <vector>
#include <optional>
#include <functional>
#include <chrono>
#include <memory>

namespace lap
{
namespace com
{
namespace discovery
{
    // ========================================================================
    // Service Instance Information (AUTOSAR Compliant)
    // ========================================================================
    
    /**
     * @brief Service instance metadata for discovery
     * @note Maps to AUTOSAR ServiceInstanceManifest
     */
    struct ServiceInstanceInfo {
        // Service identification
        std::string service_interface_name;    ///< e.g., "RadarService"
        InstanceIdentifier instance_id;        ///< e.g., 0x1234
        
        // Version information (AUTOSAR major.minor)
        uint32_t major_version;
        uint32_t minor_version;
        
        // Binding information
        std::string binding_type;              ///< "iceoryx2", "dds", "someip", "dbus"
        std::string network_endpoint;          ///< IP:Port / Topic / Service Name
        
        // Lifecycle
        uint64_t timestamp_ms;                 ///< Registration timestamp
        uint32_t ttl_seconds;                  ///< Time-to-live
        
        // Metadata (extensible)
        std::map<std::string, std::string> metadata;
        
        bool IsValid() const noexcept {
            return !service_interface_name.empty() && 
                   !binding_type.empty() &&
                   ttl_seconds > 0;
        }
    };
    
    // ========================================================================
    // Fast-DDS Discovery Server Configuration
    // ========================================================================
    
    /**
     * @brief Fast-DDS Discovery Server endpoint configuration
     * @note AUTOSAR EXP 7.2.1 - Central Service Discovery
     */
    struct DiscoveryServerEndpoint {
        std::string address;                   ///< e.g., "192.168.1.100"
        uint16_t port;                         ///< Default: 11811
        std::string transport;                 ///< "tcp", "udp", "shm"
        std::string guid_prefix;               ///< Server GUID (optional)
        
        std::string ToString() const {
            return transport + "://" + address + ":" + std::to_string(port);
        }
    };
    
    /**
     * @brief Discovery Server client configuration
     */
    struct DiscoveryServerConfig {
        std::vector<DiscoveryServerEndpoint> servers;    ///< Primary + Backup servers
        std::chrono::milliseconds connect_timeout{1000}; ///< Connection timeout
        std::chrono::milliseconds query_timeout{10};     ///< Query timeout (< 1ms target)
        uint32_t max_retry_count = 3;
        bool enable_fallback = true;                     ///< Auto fallback to dynamic discovery
    };
    
    // ========================================================================
    // Static Service Configuration (AUTOSAR R24-11 SWS_CM_02201)
    // ========================================================================
    
    /**
     * @brief Static service endpoint configuration
     * @note TPS_MANI_03312-03315 - Static service connection manifest
     */
    struct StaticServiceEndpoint {
        std::string service_interface_name;
        InstanceIdentifier instance_id;
        std::string binding_type;
        std::string endpoint;                  ///< e.g., "tcp://192.168.1.10:30500"
        
        // QoS/Transport specific
        std::map<std::string, std::string> transport_config;
    };
    
    /**
     * @brief Static service configuration loader
     * @note Conforms to AUTOSAR SWS_CM_02201 - Bypasses service discovery
     */
    class StaticServiceConfigLoader {
    public:
        /**
         * @brief Load static endpoints from YAML manifest
         * @param config_path Path to static_endpoints.yaml
         * @return Result containing loaded endpoints
         */
        static lap::core::Result<std::vector<StaticServiceEndpoint>> 
        LoadFromYAML(const std::string& config_path);
        
        /**
         * @brief Convert AUTOSAR ARXML to YAML format
         * @param arxml_path Path to AUTOSAR ARXML manifest
         * @param yaml_output_path Output YAML path
         * @return Result indicating success
         * @note Uses arxml2yaml conversion tool
         */
        static lap::core::Result<void> 
        ConvertARXMLtoYAML(const std::string& arxml_path, 
                          const std::string& yaml_output_path);
    };
    
    // ========================================================================
    // Service Discovery Manager (Three-Tier Strategy)
    // ========================================================================
    
    /**
     * @brief Core service discovery manager
     * @note Implements AUTOSAR R24-11 three-tier discovery:
     *       1. Static configuration (0ms)
     *       2. Fast-DDS Discovery Server (0.5ms)
     *       3. Dynamic discovery fallback (5-100ms)
     */
    class ServiceDiscoveryManager {
    public:
        struct Config {
            std::string static_config_path = "/etc/lap/com/static_endpoints.yaml";
            std::optional<DiscoveryServerConfig> discovery_server_config;
            bool enable_static_discovery = true;
            bool enable_central_discovery = true;
            bool enable_dynamic_discovery = true;
        };
        
        /**
         * @brief Create service discovery manager instance
         * @param config Discovery configuration
         * @return Result containing manager instance
         */
        static lap::core::Result<std::shared_ptr<ServiceDiscoveryManager>> 
        Create(const Config& config);
        
        /**
         * @brief Find service instances (synchronous)
         * @param service_interface_name Service interface name
         * @param instance_filter Optional instance ID filter
         * @param required_major_version Minimum major version (0 = any)
         * @param required_minor_version Minimum minor version (0 = any)
         * @return Result containing found service instances
         * @note Implements three-tier search with automatic fallback
         */
        lap::core::Result<std::vector<ServiceInstanceInfo>> 
        FindService(const std::string& service_interface_name,
                   const std::optional<InstanceIdentifier>& instance_filter = std::nullopt,
                   uint32_t required_major_version = 0,
                   uint32_t required_minor_version = 0);
        
        /**
         * @brief Register service instance
         * @param service_info Service metadata
         * @return Result indicating success
         * @note Registers to Discovery Server (if enabled) and local cache
         */
        lap::core::Result<void> 
        RegisterService(const ServiceInstanceInfo& service_info);
        
        /**
         * @brief Unregister service instance
         * @param instance_id Instance identifier
         * @return Result indicating success
         */
        lap::core::Result<void> 
        UnregisterService(const InstanceIdentifier& instance_id);
        
        /**
         * @brief Subscribe to service availability changes
         * @param service_interface_name Service to monitor
         * @param handler Callback for service state changes
         * @return FindServiceHandle for managing subscription
         */
        FindServiceHandle 
        StartFindService(const std::string& service_interface_name,
                        std::function<void(const std::vector<ServiceInstanceInfo>&)> handler);
        
        /**
         * @brief Stop service monitoring
         * @param handle Handle returned by StartFindService
         */
        void StopFindService(FindServiceHandle handle);
        
        /**
         * @brief Get discovery statistics
         */
        struct Statistics {
            uint64_t static_config_hits = 0;       ///< Layer 1 hits
            uint64_t discovery_server_hits = 0;    ///< Layer 2 hits
            uint64_t dynamic_discovery_hits = 0;   ///< Layer 3 hits
            uint64_t total_queries = 0;
            uint64_t failed_queries = 0;
            std::chrono::microseconds avg_latency{0};
            
            // Discovery Server health
            bool discovery_server_available = false;
            uint64_t discovery_server_failures = 0;
        };
        
        Statistics GetStatistics() const;
        
        /**
         * @brief Health check
         * @return true if at least one discovery mechanism is available
         */
        bool IsHealthy() const;
        
    private:
        ServiceDiscoveryManager(const Config& config);
        
        // Layer 1: Static configuration
        lap::core::Result<std::vector<ServiceInstanceInfo>> 
        FindInStaticConfig(const std::string& service_interface_name,
                          const std::optional<InstanceIdentifier>& instance_filter);
        
        // Layer 2: Fast-DDS Discovery Server
        lap::core::Result<std::vector<ServiceInstanceInfo>> 
        FindInDiscoveryServer(const std::string& service_interface_name,
                             const std::optional<InstanceIdentifier>& instance_filter);
        
        // Layer 3: Dynamic discovery (Binding-specific)
        lap::core::Result<std::vector<ServiceInstanceInfo>> 
        FindInDynamicDiscovery(const std::string& service_interface_name,
                              const std::optional<InstanceIdentifier>& instance_filter);
        
        class Impl;
        std::unique_ptr<Impl> pimpl_;
    };
    
    // ========================================================================
    // Fast-DDS Discovery Client Interface
    // ========================================================================
    
    /**
     * @brief Fast-DDS Discovery Server client
     * @note Implements AUTOSAR EXP 7.2.1 central service registry
     */
    class FastDdsDiscoveryClient {
    public:
        /**
         * @brief Create Discovery Server client
         * @param config Server configuration
         * @return Result containing client instance
         */
        static lap::core::Result<std::shared_ptr<FastDdsDiscoveryClient>> 
        Create(const DiscoveryServerConfig& config);
        
        /**
         * @brief Connect to Discovery Server
         * @return Result indicating success
         */
        lap::core::Result<void> Connect();
        
        /**
         * @brief Register service to Discovery Server
         * @param service_info Service metadata
         * @return Result indicating success
         */
        lap::core::Result<void> 
        RegisterService(const ServiceInstanceInfo& service_info);
        
        /**
         * @brief Find services via Discovery Server
         * @param service_interface_name Service to find
         * @param instance_filter Optional instance filter
         * @return Result containing found services
         */
        lap::core::Result<std::vector<ServiceInstanceInfo>> 
        FindService(const std::string& service_interface_name,
                   const std::optional<InstanceIdentifier>& instance_filter = std::nullopt);
        
        /**
         * @brief Subscribe to service changes via DDS Built-in Topics
         * @param handler Callback for service state changes
         * @return Result indicating success
         */
        lap::core::Result<void> 
        SubscribeServiceChanges(std::function<void(const ServiceInstanceInfo&, bool /*available*/)> handler);
        
        /**
         * @brief Check if connected to Discovery Server
         * @return true if connected
         */
        bool IsConnected() const;
        
        /**
         * @brief Disconnect from Discovery Server
         */
        void Disconnect();
        
    private:
        FastDdsDiscoveryClient(const DiscoveryServerConfig& config);
        
        class Impl;
        std::unique_ptr<Impl> pimpl_;
    };

} // namespace discovery
} // namespace com
} // namespace lap

#endif // LAP_COM_SERVICE_DISCOVERY_HPP
