// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorld2ServiceCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD2_HELLOWORLD2SERVICECDRAUX_HPP
#define FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD2_HELLOWORLD2SERVICECDRAUX_HPP

#include "HelloWorld2Service.hpp"

constexpr uint32_t lap_examples_helloworld2_SayHelloRequest_max_cdr_typesize {284UL};
constexpr uint32_t lap_examples_helloworld2_SayHelloRequest_max_key_cdr_typesize {8UL};

constexpr uint32_t lap_examples_helloworld2_NotifyLogRequest_max_cdr_typesize {284UL};
constexpr uint32_t lap_examples_helloworld2_NotifyLogRequest_max_key_cdr_typesize {8UL};

constexpr uint32_t lap_examples_helloworld2_ComputeHashResponse_max_cdr_typesize {24UL};
constexpr uint32_t lap_examples_helloworld2_ComputeHashResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld2_GreetingEvent_max_cdr_typesize {264UL};
constexpr uint32_t lap_examples_helloworld2_GreetingEvent_max_key_cdr_typesize {0UL};


constexpr uint32_t lap_examples_helloworld2_SayHelloResponse_max_cdr_typesize {276UL};
constexpr uint32_t lap_examples_helloworld2_SayHelloResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld2_DataStreamEvent_max_cdr_typesize {20UL};
constexpr uint32_t lap_examples_helloworld2_DataStreamEvent_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld2_ComputeHashRequest_max_cdr_typesize {28UL};
constexpr uint32_t lap_examples_helloworld2_ComputeHashRequest_max_key_cdr_typesize {8UL};


constexpr uint32_t lap_examples_helloworld2_StatusChangedEvent_max_cdr_typesize {8UL};
constexpr uint32_t lap_examples_helloworld2_StatusChangedEvent_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld2_AddResponse_max_cdr_typesize {20UL};
constexpr uint32_t lap_examples_helloworld2_AddResponse_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld2_GreetingMessage_max_cdr_typesize {272UL};
constexpr uint32_t lap_examples_helloworld2_GreetingMessage_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld2_DataChunk_max_cdr_typesize {16UL};
constexpr uint32_t lap_examples_helloworld2_DataChunk_max_key_cdr_typesize {0UL};

constexpr uint32_t lap_examples_helloworld2_AddRequest_max_cdr_typesize {32UL};
constexpr uint32_t lap_examples_helloworld2_AddRequest_max_key_cdr_typesize {8UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::GreetingMessage& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::DataChunk& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::GreetingEvent& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::StatusChangedEvent& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::DataStreamEvent& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::SayHelloRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::SayHelloResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::AddRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::AddResponse& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::NotifyLogRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::ComputeHashRequest& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const lap::examples::helloworld2::ComputeHashResponse& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD2_HELLOWORLD2SERVICECDRAUX_HPP

