// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorld2Service.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD2_HELLOWORLD2SERVICE_HPP
#define FAST_DDS_GENERATED__LAP_EXAMPLES_HELLOWORLD2_HELLOWORLD2SERVICE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(HELLOWORLD2SERVICE_SOURCE)
#define HELLOWORLD2SERVICE_DllAPI __declspec( dllexport )
#else
#define HELLOWORLD2SERVICE_DllAPI __declspec( dllimport )
#endif // HELLOWORLD2SERVICE_SOURCE
#else
#define HELLOWORLD2SERVICE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define HELLOWORLD2SERVICE_DllAPI
#endif // _WIN32

namespace lap {

namespace examples {

namespace helloworld2 {

const std::string SCHEMA_HASH = "f745e7d8f8138a58";
/*!
 * @brief This class represents the enumeration ErrorCode defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
enum class ErrorCode : int32_t
{
    OK,
    UNKNOWN,
    INVALID_ARG,
    OVERFLOW
};
/*!
 * @brief This class represents the enumeration ServerStatus defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
enum class ServerStatus : int32_t
{
    STARTING,
    RUNNING,
    BUSY,
    STOPPING
};
/*!
 * @brief This class represents the structure GreetingMessage defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class GreetingMessage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GreetingMessage()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GreetingMessage()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GreetingMessage that will be copied.
     */
    eProsima_user_DllExport GreetingMessage(
            const GreetingMessage& x)
    {
                    m_text = x.m_text;

                    m_timestamp = x.m_timestamp;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GreetingMessage that will be copied.
     */
    eProsima_user_DllExport GreetingMessage(
            GreetingMessage&& x) noexcept
    {
        m_text = std::move(x.m_text);
        m_timestamp = x.m_timestamp;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GreetingMessage that will be copied.
     */
    eProsima_user_DllExport GreetingMessage& operator =(
            const GreetingMessage& x)
    {

                    m_text = x.m_text;

                    m_timestamp = x.m_timestamp;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GreetingMessage that will be copied.
     */
    eProsima_user_DllExport GreetingMessage& operator =(
            GreetingMessage&& x) noexcept
    {

        m_text = std::move(x.m_text);
        m_timestamp = x.m_timestamp;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GreetingMessage object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GreetingMessage& x) const
    {
        return (m_text == x.m_text &&
           m_timestamp == x.m_timestamp);
    }

    /*!
     * @brief Comparison operator.
     * @param x GreetingMessage object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GreetingMessage& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member text
     * @param _text New value to be copied in member text
     */
    eProsima_user_DllExport void text(
            const std::string& _text)
    {
        m_text = _text;
    }

    /*!
     * @brief This function moves the value in member text
     * @param _text New value to be moved in member text
     */
    eProsima_user_DllExport void text(
            std::string&& _text)
    {
        m_text = std::move(_text);
    }

    /*!
     * @brief This function returns a constant reference to member text
     * @return Constant reference to member text
     */
    eProsima_user_DllExport const std::string& text() const
    {
        return m_text;
    }

    /*!
     * @brief This function returns a reference to member text
     * @return Reference to member text
     */
    eProsima_user_DllExport std::string& text()
    {
        return m_text;
    }


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp()
    {
        return m_timestamp;
    }



private:

    std::string m_text;
    uint64_t m_timestamp{0};

};
/*!
 * @brief This class represents the structure DataChunk defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class DataChunk
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DataChunk()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DataChunk()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DataChunk that will be copied.
     */
    eProsima_user_DllExport DataChunk(
            const DataChunk& x)
    {
                    m_sequenceNo = x.m_sequenceNo;

                    m_totalSize = x.m_totalSize;

                    m_payload = x.m_payload;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DataChunk that will be copied.
     */
    eProsima_user_DllExport DataChunk(
            DataChunk&& x) noexcept
    {
        m_sequenceNo = x.m_sequenceNo;
        m_totalSize = x.m_totalSize;
        m_payload = std::move(x.m_payload);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DataChunk that will be copied.
     */
    eProsima_user_DllExport DataChunk& operator =(
            const DataChunk& x)
    {

                    m_sequenceNo = x.m_sequenceNo;

                    m_totalSize = x.m_totalSize;

                    m_payload = x.m_payload;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DataChunk that will be copied.
     */
    eProsima_user_DllExport DataChunk& operator =(
            DataChunk&& x) noexcept
    {

        m_sequenceNo = x.m_sequenceNo;
        m_totalSize = x.m_totalSize;
        m_payload = std::move(x.m_payload);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x DataChunk object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DataChunk& x) const
    {
        return (m_sequenceNo == x.m_sequenceNo &&
           m_totalSize == x.m_totalSize &&
           m_payload == x.m_payload);
    }

    /*!
     * @brief Comparison operator.
     * @param x DataChunk object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DataChunk& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member sequenceNo
     * @param _sequenceNo New value for member sequenceNo
     */
    eProsima_user_DllExport void sequenceNo(
            uint32_t _sequenceNo)
    {
        m_sequenceNo = _sequenceNo;
    }

    /*!
     * @brief This function returns the value of member sequenceNo
     * @return Value of member sequenceNo
     */
    eProsima_user_DllExport uint32_t sequenceNo() const
    {
        return m_sequenceNo;
    }

    /*!
     * @brief This function returns a reference to member sequenceNo
     * @return Reference to member sequenceNo
     */
    eProsima_user_DllExport uint32_t& sequenceNo()
    {
        return m_sequenceNo;
    }


    /*!
     * @brief This function sets a value in member totalSize
     * @param _totalSize New value for member totalSize
     */
    eProsima_user_DllExport void totalSize(
            uint32_t _totalSize)
    {
        m_totalSize = _totalSize;
    }

    /*!
     * @brief This function returns the value of member totalSize
     * @return Value of member totalSize
     */
    eProsima_user_DllExport uint32_t totalSize() const
    {
        return m_totalSize;
    }

    /*!
     * @brief This function returns a reference to member totalSize
     * @return Reference to member totalSize
     */
    eProsima_user_DllExport uint32_t& totalSize()
    {
        return m_totalSize;
    }


    /*!
     * @brief This function copies the value in member payload
     * @param _payload New value to be copied in member payload
     */
    eProsima_user_DllExport void payload(
            const std::vector<uint8_t>& _payload)
    {
        m_payload = _payload;
    }

    /*!
     * @brief This function moves the value in member payload
     * @param _payload New value to be moved in member payload
     */
    eProsima_user_DllExport void payload(
            std::vector<uint8_t>&& _payload)
    {
        m_payload = std::move(_payload);
    }

    /*!
     * @brief This function returns a constant reference to member payload
     * @return Constant reference to member payload
     */
    eProsima_user_DllExport const std::vector<uint8_t>& payload() const
    {
        return m_payload;
    }

    /*!
     * @brief This function returns a reference to member payload
     * @return Reference to member payload
     */
    eProsima_user_DllExport std::vector<uint8_t>& payload()
    {
        return m_payload;
    }



private:

    uint32_t m_sequenceNo{0};
    uint32_t m_totalSize{0};
    std::vector<uint8_t> m_payload;

};
/*!
 * @brief This class represents the structure GreetingEvent defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class GreetingEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GreetingEvent()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GreetingEvent()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GreetingEvent that will be copied.
     */
    eProsima_user_DllExport GreetingEvent(
            const GreetingEvent& x)
    {
                    m_text = x.m_text;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GreetingEvent that will be copied.
     */
    eProsima_user_DllExport GreetingEvent(
            GreetingEvent&& x) noexcept
    {
        m_text = std::move(x.m_text);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GreetingEvent that will be copied.
     */
    eProsima_user_DllExport GreetingEvent& operator =(
            const GreetingEvent& x)
    {

                    m_text = x.m_text;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GreetingEvent that will be copied.
     */
    eProsima_user_DllExport GreetingEvent& operator =(
            GreetingEvent&& x) noexcept
    {

        m_text = std::move(x.m_text);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GreetingEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GreetingEvent& x) const
    {
        return (m_text == x.m_text);
    }

    /*!
     * @brief Comparison operator.
     * @param x GreetingEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GreetingEvent& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member text
     * @param _text New value to be copied in member text
     */
    eProsima_user_DllExport void text(
            const std::string& _text)
    {
        m_text = _text;
    }

    /*!
     * @brief This function moves the value in member text
     * @param _text New value to be moved in member text
     */
    eProsima_user_DllExport void text(
            std::string&& _text)
    {
        m_text = std::move(_text);
    }

    /*!
     * @brief This function returns a constant reference to member text
     * @return Constant reference to member text
     */
    eProsima_user_DllExport const std::string& text() const
    {
        return m_text;
    }

    /*!
     * @brief This function returns a reference to member text
     * @return Reference to member text
     */
    eProsima_user_DllExport std::string& text()
    {
        return m_text;
    }



private:

    std::string m_text;

};
/*!
 * @brief This class represents the structure StatusChangedEvent defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class StatusChangedEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport StatusChangedEvent()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~StatusChangedEvent()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object StatusChangedEvent that will be copied.
     */
    eProsima_user_DllExport StatusChangedEvent(
            const StatusChangedEvent& x)
    {
                    m_status = x.m_status;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object StatusChangedEvent that will be copied.
     */
    eProsima_user_DllExport StatusChangedEvent(
            StatusChangedEvent&& x) noexcept
    {
        m_status = x.m_status;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object StatusChangedEvent that will be copied.
     */
    eProsima_user_DllExport StatusChangedEvent& operator =(
            const StatusChangedEvent& x)
    {

                    m_status = x.m_status;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object StatusChangedEvent that will be copied.
     */
    eProsima_user_DllExport StatusChangedEvent& operator =(
            StatusChangedEvent&& x) noexcept
    {

        m_status = x.m_status;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x StatusChangedEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const StatusChangedEvent& x) const
    {
        return (m_status == x.m_status);
    }

    /*!
     * @brief Comparison operator.
     * @param x StatusChangedEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const StatusChangedEvent& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member status
     * @param _status New value for member status
     */
    eProsima_user_DllExport void status(
            ServerStatus _status)
    {
        m_status = _status;
    }

    /*!
     * @brief This function returns the value of member status
     * @return Value of member status
     */
    eProsima_user_DllExport ServerStatus status() const
    {
        return m_status;
    }

    /*!
     * @brief This function returns a reference to member status
     * @return Reference to member status
     */
    eProsima_user_DllExport ServerStatus& status()
    {
        return m_status;
    }



private:

    ServerStatus m_status{ServerStatus::STARTING};

};
/*!
 * @brief This class represents the structure DataStreamEvent defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class DataStreamEvent
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DataStreamEvent()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DataStreamEvent()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DataStreamEvent that will be copied.
     */
    eProsima_user_DllExport DataStreamEvent(
            const DataStreamEvent& x)
    {
                    m_chunk = x.m_chunk;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DataStreamEvent that will be copied.
     */
    eProsima_user_DllExport DataStreamEvent(
            DataStreamEvent&& x) noexcept
    {
        m_chunk = std::move(x.m_chunk);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DataStreamEvent that will be copied.
     */
    eProsima_user_DllExport DataStreamEvent& operator =(
            const DataStreamEvent& x)
    {

                    m_chunk = x.m_chunk;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DataStreamEvent that will be copied.
     */
    eProsima_user_DllExport DataStreamEvent& operator =(
            DataStreamEvent&& x) noexcept
    {

        m_chunk = std::move(x.m_chunk);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x DataStreamEvent object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DataStreamEvent& x) const
    {
        return (m_chunk == x.m_chunk);
    }

    /*!
     * @brief Comparison operator.
     * @param x DataStreamEvent object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DataStreamEvent& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member chunk
     * @param _chunk New value to be copied in member chunk
     */
    eProsima_user_DllExport void chunk(
            const DataChunk& _chunk)
    {
        m_chunk = _chunk;
    }

    /*!
     * @brief This function moves the value in member chunk
     * @param _chunk New value to be moved in member chunk
     */
    eProsima_user_DllExport void chunk(
            DataChunk&& _chunk)
    {
        m_chunk = std::move(_chunk);
    }

    /*!
     * @brief This function returns a constant reference to member chunk
     * @return Constant reference to member chunk
     */
    eProsima_user_DllExport const DataChunk& chunk() const
    {
        return m_chunk;
    }

    /*!
     * @brief This function returns a reference to member chunk
     * @return Reference to member chunk
     */
    eProsima_user_DllExport DataChunk& chunk()
    {
        return m_chunk;
    }



private:

    DataChunk m_chunk;

};
/*!
 * @brief This class represents the structure SayHelloRequest defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class SayHelloRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SayHelloRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SayHelloRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SayHelloRequest that will be copied.
     */
    eProsima_user_DllExport SayHelloRequest(
            const SayHelloRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_visitorName = x.m_visitorName;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SayHelloRequest that will be copied.
     */
    eProsima_user_DllExport SayHelloRequest(
            SayHelloRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_visitorName = std::move(x.m_visitorName);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SayHelloRequest that will be copied.
     */
    eProsima_user_DllExport SayHelloRequest& operator =(
            const SayHelloRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_visitorName = x.m_visitorName;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SayHelloRequest that will be copied.
     */
    eProsima_user_DllExport SayHelloRequest& operator =(
            SayHelloRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_visitorName = std::move(x.m_visitorName);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SayHelloRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SayHelloRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_visitorName == x.m_visitorName);
    }

    /*!
     * @brief Comparison operator.
     * @param x SayHelloRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SayHelloRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function copies the value in member visitorName
     * @param _visitorName New value to be copied in member visitorName
     */
    eProsima_user_DllExport void visitorName(
            const std::string& _visitorName)
    {
        m_visitorName = _visitorName;
    }

    /*!
     * @brief This function moves the value in member visitorName
     * @param _visitorName New value to be moved in member visitorName
     */
    eProsima_user_DllExport void visitorName(
            std::string&& _visitorName)
    {
        m_visitorName = std::move(_visitorName);
    }

    /*!
     * @brief This function returns a constant reference to member visitorName
     * @return Constant reference to member visitorName
     */
    eProsima_user_DllExport const std::string& visitorName() const
    {
        return m_visitorName;
    }

    /*!
     * @brief This function returns a reference to member visitorName
     * @return Reference to member visitorName
     */
    eProsima_user_DllExport std::string& visitorName()
    {
        return m_visitorName;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    std::string m_visitorName;

};
/*!
 * @brief This class represents the structure SayHelloResponse defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class SayHelloResponse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport SayHelloResponse()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~SayHelloResponse()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object SayHelloResponse that will be copied.
     */
    eProsima_user_DllExport SayHelloResponse(
            const SayHelloResponse& x)
    {
                    m_requestId = x.m_requestId;

                    m_greeting = x.m_greeting;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object SayHelloResponse that will be copied.
     */
    eProsima_user_DllExport SayHelloResponse(
            SayHelloResponse&& x) noexcept
    {
        m_requestId = x.m_requestId;
        m_greeting = std::move(x.m_greeting);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object SayHelloResponse that will be copied.
     */
    eProsima_user_DllExport SayHelloResponse& operator =(
            const SayHelloResponse& x)
    {

                    m_requestId = x.m_requestId;

                    m_greeting = x.m_greeting;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object SayHelloResponse that will be copied.
     */
    eProsima_user_DllExport SayHelloResponse& operator =(
            SayHelloResponse&& x) noexcept
    {

        m_requestId = x.m_requestId;
        m_greeting = std::move(x.m_greeting);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x SayHelloResponse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const SayHelloResponse& x) const
    {
        return (m_requestId == x.m_requestId &&
           m_greeting == x.m_greeting);
    }

    /*!
     * @brief Comparison operator.
     * @param x SayHelloResponse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const SayHelloResponse& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function copies the value in member greeting
     * @param _greeting New value to be copied in member greeting
     */
    eProsima_user_DllExport void greeting(
            const std::string& _greeting)
    {
        m_greeting = _greeting;
    }

    /*!
     * @brief This function moves the value in member greeting
     * @param _greeting New value to be moved in member greeting
     */
    eProsima_user_DllExport void greeting(
            std::string&& _greeting)
    {
        m_greeting = std::move(_greeting);
    }

    /*!
     * @brief This function returns a constant reference to member greeting
     * @return Constant reference to member greeting
     */
    eProsima_user_DllExport const std::string& greeting() const
    {
        return m_greeting;
    }

    /*!
     * @brief This function returns a reference to member greeting
     * @return Reference to member greeting
     */
    eProsima_user_DllExport std::string& greeting()
    {
        return m_greeting;
    }



private:

    uint64_t m_requestId{0};
    std::string m_greeting;

};
/*!
 * @brief This class represents the structure AddRequest defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class AddRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AddRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AddRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AddRequest that will be copied.
     */
    eProsima_user_DllExport AddRequest(
            const AddRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_a = x.m_a;

                    m_b = x.m_b;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AddRequest that will be copied.
     */
    eProsima_user_DllExport AddRequest(
            AddRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_a = x.m_a;
        m_b = x.m_b;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AddRequest that will be copied.
     */
    eProsima_user_DllExport AddRequest& operator =(
            const AddRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_a = x.m_a;

                    m_b = x.m_b;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AddRequest that will be copied.
     */
    eProsima_user_DllExport AddRequest& operator =(
            AddRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_a = x.m_a;
        m_b = x.m_b;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x AddRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const AddRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_a == x.m_a &&
           m_b == x.m_b);
    }

    /*!
     * @brief Comparison operator.
     * @param x AddRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const AddRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member a
     * @param _a New value for member a
     */
    eProsima_user_DllExport void a(
            uint32_t _a)
    {
        m_a = _a;
    }

    /*!
     * @brief This function returns the value of member a
     * @return Value of member a
     */
    eProsima_user_DllExport uint32_t a() const
    {
        return m_a;
    }

    /*!
     * @brief This function returns a reference to member a
     * @return Reference to member a
     */
    eProsima_user_DllExport uint32_t& a()
    {
        return m_a;
    }


    /*!
     * @brief This function sets a value in member b
     * @param _b New value for member b
     */
    eProsima_user_DllExport void b(
            uint32_t _b)
    {
        m_b = _b;
    }

    /*!
     * @brief This function returns the value of member b
     * @return Value of member b
     */
    eProsima_user_DllExport uint32_t b() const
    {
        return m_b;
    }

    /*!
     * @brief This function returns a reference to member b
     * @return Reference to member b
     */
    eProsima_user_DllExport uint32_t& b()
    {
        return m_b;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    uint32_t m_a{0};
    uint32_t m_b{0};

};
/*!
 * @brief This class represents the structure AddResponse defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class AddResponse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AddResponse()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AddResponse()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AddResponse that will be copied.
     */
    eProsima_user_DllExport AddResponse(
            const AddResponse& x)
    {
                    m_requestId = x.m_requestId;

                    m_sum = x.m_sum;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AddResponse that will be copied.
     */
    eProsima_user_DllExport AddResponse(
            AddResponse&& x) noexcept
    {
        m_requestId = x.m_requestId;
        m_sum = x.m_sum;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AddResponse that will be copied.
     */
    eProsima_user_DllExport AddResponse& operator =(
            const AddResponse& x)
    {

                    m_requestId = x.m_requestId;

                    m_sum = x.m_sum;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AddResponse that will be copied.
     */
    eProsima_user_DllExport AddResponse& operator =(
            AddResponse&& x) noexcept
    {

        m_requestId = x.m_requestId;
        m_sum = x.m_sum;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x AddResponse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const AddResponse& x) const
    {
        return (m_requestId == x.m_requestId &&
           m_sum == x.m_sum);
    }

    /*!
     * @brief Comparison operator.
     * @param x AddResponse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const AddResponse& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member sum
     * @param _sum New value for member sum
     */
    eProsima_user_DllExport void sum(
            uint32_t _sum)
    {
        m_sum = _sum;
    }

    /*!
     * @brief This function returns the value of member sum
     * @return Value of member sum
     */
    eProsima_user_DllExport uint32_t sum() const
    {
        return m_sum;
    }

    /*!
     * @brief This function returns a reference to member sum
     * @return Reference to member sum
     */
    eProsima_user_DllExport uint32_t& sum()
    {
        return m_sum;
    }



private:

    uint64_t m_requestId{0};
    uint32_t m_sum{0};

};
/*!
 * @brief This class represents the structure NotifyLogRequest defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class NotifyLogRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport NotifyLogRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~NotifyLogRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object NotifyLogRequest that will be copied.
     */
    eProsima_user_DllExport NotifyLogRequest(
            const NotifyLogRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_message = x.m_message;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object NotifyLogRequest that will be copied.
     */
    eProsima_user_DllExport NotifyLogRequest(
            NotifyLogRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_message = std::move(x.m_message);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object NotifyLogRequest that will be copied.
     */
    eProsima_user_DllExport NotifyLogRequest& operator =(
            const NotifyLogRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_message = x.m_message;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object NotifyLogRequest that will be copied.
     */
    eProsima_user_DllExport NotifyLogRequest& operator =(
            NotifyLogRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_message = std::move(x.m_message);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x NotifyLogRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const NotifyLogRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_message == x.m_message);
    }

    /*!
     * @brief Comparison operator.
     * @param x NotifyLogRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const NotifyLogRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message)
    {
        m_message = _message;
    }

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message)
    {
        m_message = std::move(_message);
    }

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const
    {
        return m_message;
    }

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message()
    {
        return m_message;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    std::string m_message;

};
/*!
 * @brief This class represents the structure ComputeHashRequest defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class ComputeHashRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ComputeHashRequest()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ComputeHashRequest()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ComputeHashRequest that will be copied.
     */
    eProsima_user_DllExport ComputeHashRequest(
            const ComputeHashRequest& x)
    {
                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ComputeHashRequest that will be copied.
     */
    eProsima_user_DllExport ComputeHashRequest(
            ComputeHashRequest&& x) noexcept
    {
        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_data = std::move(x.m_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ComputeHashRequest that will be copied.
     */
    eProsima_user_DllExport ComputeHashRequest& operator =(
            const ComputeHashRequest& x)
    {

                    m_serviceId = x.m_serviceId;

                    m_instanceId = x.m_instanceId;

                    m_requestId = x.m_requestId;

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ComputeHashRequest that will be copied.
     */
    eProsima_user_DllExport ComputeHashRequest& operator =(
            ComputeHashRequest&& x) noexcept
    {

        m_serviceId = x.m_serviceId;
        m_instanceId = x.m_instanceId;
        m_requestId = x.m_requestId;
        m_data = std::move(x.m_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ComputeHashRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ComputeHashRequest& x) const
    {
        return (m_serviceId == x.m_serviceId &&
           m_instanceId == x.m_instanceId &&
           m_requestId == x.m_requestId &&
           m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x ComputeHashRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ComputeHashRequest& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member serviceId
     * @param _serviceId New value for member serviceId
     */
    eProsima_user_DllExport void serviceId(
            uint32_t _serviceId)
    {
        m_serviceId = _serviceId;
    }

    /*!
     * @brief This function returns the value of member serviceId
     * @return Value of member serviceId
     */
    eProsima_user_DllExport uint32_t serviceId() const
    {
        return m_serviceId;
    }

    /*!
     * @brief This function returns a reference to member serviceId
     * @return Reference to member serviceId
     */
    eProsima_user_DllExport uint32_t& serviceId()
    {
        return m_serviceId;
    }


    /*!
     * @brief This function sets a value in member instanceId
     * @param _instanceId New value for member instanceId
     */
    eProsima_user_DllExport void instanceId(
            uint32_t _instanceId)
    {
        m_instanceId = _instanceId;
    }

    /*!
     * @brief This function returns the value of member instanceId
     * @return Value of member instanceId
     */
    eProsima_user_DllExport uint32_t instanceId() const
    {
        return m_instanceId;
    }

    /*!
     * @brief This function returns a reference to member instanceId
     * @return Reference to member instanceId
     */
    eProsima_user_DllExport uint32_t& instanceId()
    {
        return m_instanceId;
    }


    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::vector<uint8_t>& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::vector<uint8_t>&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::vector<uint8_t>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::vector<uint8_t>& data()
    {
        return m_data;
    }



private:

    uint32_t m_serviceId{0};
    uint32_t m_instanceId{0};
    uint64_t m_requestId{0};
    std::vector<uint8_t> m_data;

};
/*!
 * @brief This class represents the structure ComputeHashResponse defined by the user in the IDL file.
 * @ingroup HelloWorld2Service
 */
class ComputeHashResponse
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ComputeHashResponse()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ComputeHashResponse()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ComputeHashResponse that will be copied.
     */
    eProsima_user_DllExport ComputeHashResponse(
            const ComputeHashResponse& x)
    {
                    m_requestId = x.m_requestId;

                    m_hash = x.m_hash;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ComputeHashResponse that will be copied.
     */
    eProsima_user_DllExport ComputeHashResponse(
            ComputeHashResponse&& x) noexcept
    {
        m_requestId = x.m_requestId;
        m_hash = x.m_hash;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ComputeHashResponse that will be copied.
     */
    eProsima_user_DllExport ComputeHashResponse& operator =(
            const ComputeHashResponse& x)
    {

                    m_requestId = x.m_requestId;

                    m_hash = x.m_hash;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ComputeHashResponse that will be copied.
     */
    eProsima_user_DllExport ComputeHashResponse& operator =(
            ComputeHashResponse&& x) noexcept
    {

        m_requestId = x.m_requestId;
        m_hash = x.m_hash;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ComputeHashResponse object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ComputeHashResponse& x) const
    {
        return (m_requestId == x.m_requestId &&
           m_hash == x.m_hash);
    }

    /*!
     * @brief Comparison operator.
     * @param x ComputeHashResponse object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ComputeHashResponse& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member requestId
     * @param _requestId New value for member requestId
     */
    eProsima_user_DllExport void requestId(
            uint64_t _requestId)
    {
        m_requestId = _requestId;
    }

    /*!
     * @brief This function returns the value of member requestId
     * @return Value of member requestId
     */
    eProsima_user_DllExport uint64_t requestId() const
    {
        return m_requestId;
    }

    /*!
     * @brief This function returns a reference to member requestId
     * @return Reference to member requestId
     */
    eProsima_user_DllExport uint64_t& requestId()
    {
        return m_requestId;
    }


    /*!
     * @brief This function sets a value in member hash
     * @param _hash New value for member hash
     */
    eProsima_user_DllExport void hash(
            uint64_t _hash)
    {
        m_hash = _hash;
    }

    /*!
     * @brief This function returns the value of member hash
     * @return Value of member hash
     */
    eProsima_user_DllExport uint64_t hash() const
    {
        return m_hash;
    }

    /*!
     * @brief This function returns a reference to member hash
     * @return Reference to member hash
     */
    eProsima_user_DllExport uint64_t& hash()
    {
        return m_hash;
    }



private:

    uint64_t m_requestId{0};
    uint64_t m_hash{0};

};

} // namespace helloworld2

} // namespace examples

} // namespace lap

#endif // _FAST_DDS_GENERATED_LAP_EXAMPLES_HELLOWORLD2_HELLOWORLD2SERVICE_HPP_


